//! Rendering of `/etc/btrbk/btrbk.conf` from `config.toml`.
//!
//! Lives in the library, not in `setup/`, because the backup run itself
//! regenerates this file when it adopts or retires a subvolume (`adopt.rs`).

use std::path::Path;

use crate::config::{Config, Retention, SubvolConfig, Target, TargetRole};

pub const GENERATED_HEADER: &str = "\
# Generated by btrdasd setup — do not edit.\n\
# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n";

/// Generate btrbk.conf with global settings, per-source volume blocks (one block
/// per source with all matching targets), and per-subvolume snapshot names.
pub fn render_btrbk_conf(config: &Config) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');

    // Global settings
    out.push_str("# Global settings\n");
    out.push_str("transaction_log         /var/log/btrbk.log\n");
    out.push_str("stream_buffer           256m\n");
    out.push_str("stream_compress         zstd\n");
    out.push_str("lockfile                /var/lock/btrbk.lock\n\n");

    // Source retention
    out.push_str("# Source snapshots — minimal, for send reference\n");
    out.push_str("snapshot_preserve_min   latest\n");
    out.push_str("snapshot_preserve       2d\n\n");

    // Find the primary target to use as the global retention baseline
    let primary = config
        .targets
        .iter()
        .find(|t| t.role == TargetRole::Primary);
    if let Some(p) = primary {
        out.push_str(&format!("# Default target retention (from {})\n", p.label));
        out.push_str("target_preserve_min     latest\n");
        out.push_str(&format!(
            "target_preserve         {}\n\n",
            format_retention(&p.retention)
        ));
    }

    // One volume block per source, with all matching targets inline
    for source in &config.sources {
        let targets: Vec<&Target> = config
            .targets
            .iter()
            .filter(|t| t.role == TargetRole::Primary || t.role == TargetRole::Mirror)
            .filter(|t| source.target_labels.is_empty() || source.target_labels.contains(&t.label))
            .collect();

        if targets.is_empty() {
            continue;
        }

        // Retired entries are not sent; a source left with none has no block.
        let snap_names = resolve_snapshot_names(&source.subvolumes);
        let live: Vec<(&SubvolConfig, &String)> = source
            .subvolumes
            .iter()
            .zip(snap_names.iter())
            .filter(|(sv, _)| sv.retired.is_none())
            .collect();
        if live.is_empty() {
            continue;
        }

        // Determine the target subdir for this source
        let subdir = source.target_subdirs.first().unwrap_or(&source.label);

        out.push_str(&format!("# {}\n", source.label));
        out.push_str(&format!("volume {}\n", source.volume));
        out.push_str(&format!(
            "  snapshot_dir          {}\n",
            source.snapshot_dir
        ));

        // Emit target lines with per-target retention overrides
        for target in &targets {
            out.push_str(&format!(
                "  target                {}/{}\n",
                target.mount, subdir
            ));
            // If this target's retention differs from primary, emit an override
            if let Some(p) = primary
                && target.label != p.label
                && target.retention != p.retention
            {
                out.push_str(&format!(
                    "    target_preserve     {}\n",
                    format_retention(&target.retention)
                ));
            }
        }
        out.push('\n');

        for (subvol, snap_name) in live {
            out.push_str(&format!("  subvolume             {}\n", subvol.name));
            out.push_str(&format!("    snapshot_name       {snap_name}\n\n"));
        }
    }

    out
}

/// Format a Retention struct into btrbk's preserve format (e.g., "4w 12m 4y").
fn format_retention(r: &Retention) -> String {
    let mut parts = Vec::new();
    if r.daily > 0 {
        parts.push(format!("{}d", r.daily));
    }
    if r.weekly > 0 {
        parts.push(format!("{}w", r.weekly));
    }
    if r.monthly > 0 {
        parts.push(format!("{}m", r.monthly));
    }
    if r.yearly > 0 {
        parts.push(format!("{}y", r.yearly));
    }
    if parts.is_empty() {
        "4w".to_string()
    } else {
        parts.join(" ")
    }
}

/// The snapshot name btrbk would be given for a subvolume with no explicit
/// `snapshot_name`: `@` removed, `/` flattened to `-`, and `root` for the
/// bare top-level subvolume.
pub fn algorithmic_snapshot_name(subvol_name: &str) -> String {
    let stripped = subvol_name.replace('@', "").replace('/', "-");
    if stripped.is_empty() {
        "root".to_string()
    } else {
        stripped
    }
}

/// Resolve snapshot names for a list of subvolumes, using explicit overrides
/// where present and generating safe algorithmic names otherwise.
/// On a collision the colliding names get a `root-` prefix. That does not
/// separate two algorithmic names that both resolve the same way (`@home` and
/// `home` both become `root-home`).
pub fn resolve_snapshot_names(subvols: &[SubvolConfig]) -> Vec<String> {
    use std::collections::HashMap;

    let mut names: Vec<String> = subvols
        .iter()
        .map(|sv| {
            if let Some(ref name) = sv.snapshot_name {
                return name.clone();
            }
            algorithmic_snapshot_name(&sv.name)
        })
        .collect();

    // Detect and resolve collisions by appending the full subvol name
    let mut counts: HashMap<String, usize> = HashMap::new();
    for name in &names {
        *counts.entry(name.clone()).or_insert(0) += 1;
    }

    for (i, name) in names.clone().iter().enumerate() {
        if counts[name] > 1 && subvols[i].snapshot_name.is_none() {
            // Disambiguate: use the full subvol name with @ → "" and special chars → "-"
            let disambiguated = algorithmic_snapshot_name(&subvols[i].name);
            // If still the same, prepend "root-" for the bare @ case
            if disambiguated == *name {
                names[i] = format!("root-{}", subvols[i].name.replace('@', ""));
            } else {
                names[i] = disambiguated;
            }
        }
    }

    names
}

/// Save an edited config and regenerate btrbk.conf from it, or change
/// neither. Every path that edits `config.toml` outside a sync — the CLI's
/// `subvol` commands and every D-Bus helper method that saves — goes through
/// this, so the two files cannot drift apart by that route. An entry that is in config.toml but not in btrbk.conf is not
/// backed up, however it looks.
pub fn save_config_and_btrbk_conf(
    cfg: &Config,
    config_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    save_config_and_btrbk_conf_with(cfg, config_path, &|cfg, path| cfg.save(path))
}

type ConfigSaver<'a> = dyn Fn(&Config, &Path) -> Result<(), Box<dyn std::error::Error>> + 'a;

/// `save_config_and_btrbk_conf` with the config save injectable, so a test can
/// make that step fail in ways a real filesystem will not on demand.
fn save_config_and_btrbk_conf_with(
    cfg: &Config,
    config_path: &Path,
    save: &ConfigSaver<'_>,
) -> Result<(), Box<dyn std::error::Error>> {
    let errors = cfg.validate();
    if !errors.is_empty() {
        return Err(errors.join("\n").into());
    }
    let conf_path = Path::new(&cfg.general.btrbk_conf);
    // Absent is a state to restore (by removing what we write); unreadable is
    // not, because then a failed save could not be undone. Refuse that case.
    let previous = match std::fs::read_to_string(conf_path) {
        Ok(text) => Some(text),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            return Err(format!(
                "cannot read {} to keep a rollback copy: {e}",
                conf_path.display()
            )
            .into());
        }
    };
    crate::fsutil::write_atomic(conf_path, &render_btrbk_conf(cfg))?;
    if let Err(e) = save(cfg, config_path) {
        let rollback = match &previous {
            Some(text) => crate::fsutil::write_atomic(conf_path, text),
            None => std::fs::remove_file(conf_path),
        };
        if let Err(re) = rollback {
            return Err(format!(
                "{e}; rolling back {} also failed: {re} — {} and {} may disagree",
                conf_path.display(),
                config_path.display(),
                conf_path.display()
            )
            .into());
        }
        return Err(e);
    }
    Ok(())
}

#[cfg(test)]
mod tests {

    #[test]
    fn retired_entries_and_all_retired_sources_are_not_rendered() {
        let mut cfg = test_config();
        cfg.sources[0].subvolumes[0].retired = Some("2026-01-01".into());
        let text = render_btrbk_conf(&cfg);
        let gone = &cfg.sources[0].subvolumes[0].name;
        assert!(
            !text.contains(&format!("subvolume             {gone}\n")),
            "{text}"
        );

        for sv in &mut cfg.sources[0].subvolumes {
            sv.retired = Some("2026-01-01".into());
        }
        let text = render_btrbk_conf(&cfg);
        assert!(
            !text.contains(&format!("# {}\n", cfg.sources[0].label)),
            "{text}"
        );
    }
    use super::*;
    use crate::config::Source;

    fn test_config() -> Config {
        let mut config = Config::default();
        config.general.install_prefix = "/usr/local".to_string();
        config.sources.push(Source {
            label: "nvme-root".to_string(),
            volume: "/.btrfs-nvme".to_string(),
            subvolumes: vec![
                SubvolConfig {
                    name: "@".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                    ..Default::default()
                },
                SubvolConfig {
                    name: "@home".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                    ..Default::default()
                },
            ],
            device: "/dev/nvme0n1p2".to_string(),
            snapshot_dir: ".btrbk-snapshots".into(),
            target_subdirs: vec!["nvme".into()],
            target_labels: vec![],
        });
        config.targets.push(Target {
            label: "primary-22tb".to_string(),
            serial: "ZXA0LMAE".to_string(),
            serials: vec!["ZXA0LMAE".to_string()],
            mount_uuid: None,
            mount: "/mnt/backup-22tb".to_string(),
            role: TargetRole::Primary,
            retention: Retention {
                weekly: 4,
                monthly: 2,
                daily: 0,
                yearly: 0,
            },
            display_name: String::new(),
        });
        config
    }

    #[test]
    fn algorithmic_snapshot_name_strips_at_and_flattens_slashes() {
        assert_eq!(algorithmic_snapshot_name("@home"), "home");
        assert_eq!(
            algorithmic_snapshot_name("@srv/stremio-web"),
            "srv-stremio-web"
        );
        assert_eq!(
            algorithmic_snapshot_name("bosco-media/video"),
            "bosco-media-video"
        );
        // The bare top-level subvolume has nothing left once '@' is gone.
        assert_eq!(algorithmic_snapshot_name("@"), "root");
    }

    #[test]
    fn render_btrbk_conf_test() {
        let config = test_config();
        let result = render_btrbk_conf(&config);
        // Check volume, subvolume, target, retention, header
        assert!(result.contains("volume /.btrfs-nvme"), "missing volume");
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.trim().ends_with("@")),
            "missing subvolume @"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.contains("@home")),
            "missing subvolume @home"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("target") && l.contains("/mnt/backup-22tb")),
            "missing target /mnt/backup-22tb"
        );
        assert!(result.contains("4w 2m"), "missing retention 4w 2m");
        assert!(
            result.contains("# Generated by btrdasd setup"),
            "missing header"
        );
        // Verify per-source snapshot_dir is used (not hardcoded)
        assert!(
            result.contains("snapshot_dir          .btrbk-snapshots"),
            "missing default snapshot_dir"
        );
    }

    #[test]
    fn render_btrbk_conf_uses_per_source_snapshot_dir() {
        let mut config = test_config();
        // Add a second source with a different snapshot_dir
        config.sources.push(Source {
            label: "hdd-projects".to_string(),
            volume: "/.btrfs-hdd".to_string(),
            subvolumes: vec![SubvolConfig {
                name: "ClaudeCodeProjects".to_string(),
                manual_only: false,
                snapshot_name: None,
                ..Default::default()
            }],
            device: "/dev/sda".to_string(),
            snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".into(),
            target_subdirs: vec![],
            target_labels: vec![],
        });
        let result = render_btrbk_conf(&config);
        // The HDD source must use its custom snapshot_dir, not the default
        assert!(
            result.contains("snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots"),
            "btrbk.conf must use per-source snapshot_dir, got:\n{result}"
        );
    }

    fn subvol(name: &str, snapshot_name: Option<&str>) -> SubvolConfig {
        SubvolConfig {
            name: name.to_string(),
            manual_only: false,
            snapshot_name: snapshot_name.map(str::to_string),
            ..Default::default()
        }
    }

    fn retention(daily: u32, weekly: u32, monthly: u32, yearly: u32) -> Retention {
        Retention {
            weekly,
            monthly,
            daily,
            yearly,
        }
    }

    fn target(label: &str, mount: &str, role: TargetRole, retention: Retention) -> Target {
        Target {
            label: label.to_string(),
            serial: String::new(),
            serials: vec![],
            mount_uuid: None,
            mount: mount.to_string(),
            role,
            retention,
            display_name: String::new(),
        }
    }

    /// The shape of the author's deployment (`.claude/rules/backup.md`
    /// §Targets and Retention): one long-retention primary that receives
    /// everything, two short-retention recovery drives that receive only
    /// system data, a system source that fans out to all three, and a bulk
    /// source scoped to the primary alone.
    fn multi_target_config() -> Config {
        let targets = vec![
            target(
                "primary-22tb",
                "/mnt/backup-22tb",
                TargetRole::Primary,
                retention(7, 4, 12, 1),
            ),
            target(
                "system-recovery-A-2tb",
                "/mnt/backup-system-recovery-A",
                TargetRole::Mirror,
                retention(7, 0, 0, 0),
            ),
            target(
                "system-recovery-B-2tb",
                "/mnt/backup-system-recovery-B",
                TargetRole::Mirror,
                retention(7, 0, 0, 0),
            ),
        ];
        let sources = vec![
            Source {
                label: "nvme".to_string(),
                volume: "/.btrfs-nvme".to_string(),
                subvolumes: vec![
                    subvol("@", None),
                    subvol("@home", None),
                    subvol("@root", None),
                    subvol("@var/log", None),
                ],
                device: "/dev/nvme0n1p2".to_string(),
                snapshot_dir: ".btrbk-snapshots".to_string(),
                target_subdirs: vec!["nvme".to_string()],
                target_labels: vec![],
            },
            Source {
                label: "hdd-projects".to_string(),
                volume: "/.btrfs-hdd".to_string(),
                subvolumes: vec![
                    subvol("ClaudeCodeProjects", None),
                    subvol(
                        "ClaudeCodeProjects/DAS-Backup-Manager",
                        Some("das-backup-manager"),
                    ),
                ],
                device: "/dev/sda".to_string(),
                snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".to_string(),
                target_subdirs: vec![],
                target_labels: vec!["primary-22tb".to_string()],
            },
            Source {
                label: "retired".to_string(),
                volume: "/.btrfs-retired".to_string(),
                subvolumes: vec![subvol("data", None)],
                device: "/dev/sdz".to_string(),
                snapshot_dir: ".btrbk-snapshots".to_string(),
                target_subdirs: vec![],
                target_labels: vec!["no-such-target".to_string()],
            },
        ];
        Config {
            targets,
            sources,
            ..Config::default()
        }
    }

    #[test]
    fn render_btrbk_conf_renders_the_whole_file_for_a_multi_target_config() {
        // Asserted in full because every line is load-bearing: the `target`
        // lines decide which drive a subvolume is sent to, the
        // `target_preserve` lines decide how long it is kept there, and
        // `snapshot_name` is the on-disk identity of each send/receive chain.
        let expected = concat!(
            "# Generated by btrdasd setup — do not edit.\n",
            "# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n",
            "\n",
            "# Global settings\n",
            "transaction_log         /var/log/btrbk.log\n",
            "stream_buffer           256m\n",
            "stream_compress         zstd\n",
            "lockfile                /var/lock/btrbk.lock\n",
            "\n",
            "# Source snapshots — minimal, for send reference\n",
            "snapshot_preserve_min   latest\n",
            "snapshot_preserve       2d\n",
            "\n",
            "# Default target retention (from primary-22tb)\n",
            "target_preserve_min     latest\n",
            "target_preserve         7d 4w 12m 1y\n",
            "\n",
            // target_labels = [] fans out to every target. The primary
            // inherits the global retention; each recovery drive carries its
            // own shorter one as an override.
            "# nvme\n",
            "volume /.btrfs-nvme\n",
            "  snapshot_dir          .btrbk-snapshots\n",
            "  target                /mnt/backup-22tb/nvme\n",
            "  target                /mnt/backup-system-recovery-A/nvme\n",
            "    target_preserve     7d\n",
            "  target                /mnt/backup-system-recovery-B/nvme\n",
            "    target_preserve     7d\n",
            "\n",
            // `@` and `@root` both strip to `root`; btrbk refuses two
            // subvolumes that would write the same snapshot, so both are
            // renamed. `forget::parse_subvol_snapshot_names` and
            // `backup-run.sh` rely on exactly these two names.
            "  subvolume             @\n",
            "    snapshot_name       root-\n",
            "\n",
            "  subvolume             @home\n",
            "    snapshot_name       home\n",
            "\n",
            "  subvolume             @root\n",
            "    snapshot_name       root-root\n",
            "\n",
            "  subvolume             @var/log\n",
            "    snapshot_name       var-log\n",
            "\n",
            // Scoped to the primary: bulk data must never reach the 2 TB
            // recovery drives. No target_subdirs, so the label is the subdir.
            "# hdd-projects\n",
            "volume /.btrfs-hdd\n",
            "  snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots\n",
            "  target                /mnt/backup-22tb/hdd-projects\n",
            "\n",
            "  subvolume             ClaudeCodeProjects\n",
            "    snapshot_name       ClaudeCodeProjects\n",
            "\n",
            "  subvolume             ClaudeCodeProjects/DAS-Backup-Manager\n",
            "    snapshot_name       das-backup-manager\n",
            "\n",
            // "retired" names a target that is not configured, so it gets no
            // volume block at all: a block without a target line would make
            // btrbk snapshot the source and send it nowhere.
        );
        assert_eq!(render_btrbk_conf(&multi_target_config()), expected);
    }

    #[test]
    fn render_btrbk_conf_overrides_retention_only_where_it_differs_from_the_primary() {
        // A mirror with the primary's own retention inherits the global
        // `target_preserve`; repeating it per target would be noise that
        // hides the overrides which do matter.
        let mut config = multi_target_config();
        config.targets[1].retention = config.targets[0].retention.clone();
        let result = render_btrbk_conf(&config);
        assert!(
            result.contains(concat!(
                "  target                /mnt/backup-22tb/nvme\n",
                "  target                /mnt/backup-system-recovery-A/nvme\n",
                "  target                /mnt/backup-system-recovery-B/nvme\n",
                "    target_preserve     7d\n",
                "\n",
            )),
            "{result}"
        );
        assert_eq!(result.matches("    target_preserve     ").count(), 1);
    }

    #[test]
    fn render_btrbk_conf_scopes_a_source_to_a_mirror_alone() {
        // target_labels selects by label, whatever the target's role.
        let mut config = multi_target_config();
        config.sources[0].target_labels = vec!["system-recovery-B-2tb".to_string()];
        let result = render_btrbk_conf(&config);
        assert!(
            result.contains(concat!(
                "volume /.btrfs-nvme\n",
                "  snapshot_dir          .btrbk-snapshots\n",
                "  target                /mnt/backup-system-recovery-B/nvme\n",
                "    target_preserve     7d\n",
                "\n",
            )),
            "{result}"
        );
        assert!(!result.contains("/mnt/backup-22tb/nvme"), "{result}");
        assert!(
            !result.contains("/mnt/backup-system-recovery-A/nvme"),
            "{result}"
        );
    }

    #[test]
    fn format_retention_emits_only_the_non_zero_periods() {
        // A period the config leaves at zero is omitted, in the fixed order
        // daily, weekly, monthly, yearly; 1 is the smallest count that must
        // be rendered. This string is each target's whole retention policy.
        let cases = [
            (retention(7, 4, 12, 1), "7d 4w 12m 1y"),
            (retention(1, 1, 1, 1), "1d 1w 1m 1y"),
            (retention(7, 0, 0, 0), "7d"),
            (retention(0, 4, 0, 0), "4w"),
            (retention(0, 0, 12, 0), "12m"),
            (retention(0, 0, 0, 1), "1y"),
            (retention(1, 0, 0, 0), "1d"),
            (retention(0, 1, 0, 0), "1w"),
            (retention(0, 0, 1, 0), "1m"),
            (retention(0, 4, 2, 0), "4w 2m"),
            (retention(7, 0, 0, 2), "7d 2y"),
            (retention(0, 4, 12, 4), "4w 12m 4y"),
        ];
        for (retention, expected) in cases {
            assert_eq!(format_retention(&retention), expected, "{retention:?}");
        }
    }

    #[test]
    fn format_retention_falls_back_to_four_weeks_when_every_period_is_zero() {
        // An all-zero retention must not leave `target_preserve` without an
        // argument, nor render "0d 0w 0m 0y"; it gets the four-week fallback.
        assert_eq!(format_retention(&retention(0, 0, 0, 0)), "4w");
        assert_eq!(format_retention(&Retention::default()), "4w");
    }

    fn snapshot_names(subvols: &[(&str, Option<&str>)]) -> Vec<String> {
        let subvols: Vec<SubvolConfig> = subvols
            .iter()
            .map(|(name, snapshot_name)| subvol(name, *snapshot_name))
            .collect();
        resolve_snapshot_names(&subvols)
    }

    #[test]
    fn resolve_snapshot_names_leaves_unique_names_alone() {
        // The name is the identity of an existing send/receive chain:
        // renaming a subvolume that collides with nothing would strand every
        // snapshot already taken of it.
        assert_eq!(
            snapshot_names(&[
                ("@", None),
                ("@home", None),
                ("@var/log", None),
                ("ClaudeCodeProjects", None),
                ("Audiobooks", Some("books")),
            ]),
            ["root", "home", "var-log", "ClaudeCodeProjects", "books"]
        );
    }

    #[test]
    fn resolve_snapshot_names_renames_only_the_colliding_subvolumes() {
        // The production case (bd DAS-Backup-Manager-5ig, -ycr): `@` and
        // `@root` both strip to `root`. Their neighbours keep their names.
        assert_eq!(
            snapshot_names(&[
                ("@", None),
                ("@home", None),
                ("@root", None),
                ("@opt", None)
            ]),
            ["root-", "home", "root-root", "opt"]
        );
    }

    #[test]
    fn resolve_snapshot_names_never_rewrites_an_explicit_name() {
        // An explicit snapshot_name is the operator's decision. When it
        // collides with an algorithmic name, the algorithmic one moves.
        assert_eq!(
            snapshot_names(&[("@home", None), ("users", Some("home"))]),
            ["root-home", "home"]
        );
        assert_eq!(
            snapshot_names(&[("users", Some("home")), ("@home", None), ("@opt", None)]),
            ["home", "root-home", "opt"]
        );
    }

    // ---- subvol config editing: config.toml and btrbk.conf change together ----

    fn saveable_config(dir: &Path) -> Config {
        let text = format!(
            r#"[general]
version = "0.7.22"
install_prefix = "/usr"
db_path = "{db}"
btrbk_conf = "{conf}"
[init]
system = "systemd"
[schedule]
incremental = "03:00"
full = "Sun 04:00"
randomized_delay_min = 30
[[source]]
label = "s"
volume = "/vol"
device = "UUID=abc"
[[source.subvolumes]]
name = "@"
[[target]]
label = "t"
serial = "X"
mount = "/mnt/t"
role = "primary"
[target.retention]
daily = 7
[email]
enabled = false
[gui]
enabled = false
"#,
            db = dir.join("index.db").display(),
            conf = dir.join("btrbk.conf").display(),
        );
        Config::from_toml(&text).unwrap()
    }

    #[test]
    fn save_writes_config_and_btrbk_conf_that_agree() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let config_path = dir.path().join("config.toml");
        save_config_and_btrbk_conf(&cfg, &config_path).unwrap();

        let reloaded = Config::load(&config_path).unwrap();
        assert_eq!(reloaded.to_toml().unwrap(), cfg.to_toml().unwrap());
        let conf = std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap();
        assert_eq!(conf, render_btrbk_conf(&reloaded));
    }

    #[test]
    fn save_of_an_invalid_config_writes_neither_file() {
        let dir = tempfile::tempdir().unwrap();
        let mut cfg = saveable_config(dir.path());
        cfg.schedule.incremental = "not a time".into();
        assert!(!cfg.validate().is_empty(), "fixture must be invalid");
        let config_path = dir.path().join("config.toml");
        let err = save_config_and_btrbk_conf(&cfg, &config_path).unwrap_err();
        assert!(!err.to_string().is_empty());
        assert!(!config_path.exists());
        assert!(!dir.path().join("btrbk.conf").exists());
    }

    #[test]
    fn failed_config_save_restores_the_previous_btrbk_conf() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let conf_path = dir.path().join("btrbk.conf");
        std::fs::write(&conf_path, "previous btrbk.conf\n").unwrap();
        // Occupy the atomic writer's temp name so the config save fails.
        std::fs::create_dir(dir.path().join(".config.toml.tmp")).unwrap();
        let config_path = dir.path().join("config.toml");

        assert!(save_config_and_btrbk_conf(&cfg, &config_path).is_err());
        assert_eq!(
            std::fs::read_to_string(&conf_path).unwrap(),
            "previous btrbk.conf\n"
        );
        assert!(!config_path.exists());
    }

    #[test]
    fn failed_config_save_leaves_no_btrbk_conf_when_there_was_none() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        std::fs::create_dir(dir.path().join(".config.toml.tmp")).unwrap();
        let config_path = dir.path().join("config.toml");

        assert!(save_config_and_btrbk_conf(&cfg, &config_path).is_err());
        assert!(!dir.path().join("btrbk.conf").exists());
    }

    #[test]
    fn a_failed_rollback_is_reported_and_names_both_files() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let conf_path = dir.path().join("btrbk.conf");
        let config_path = dir.path().join("config.toml");
        // The save fails and, on the way out, leaves a directory where the
        // rollback needs a file: both the restore and the removal fail.
        let sabotage = |_: &Config, _: &Path| -> Result<(), Box<dyn std::error::Error>> {
            std::fs::remove_file(&conf_path).unwrap();
            std::fs::create_dir(&conf_path).unwrap();
            Err("save failed".into())
        };

        // Case 1: there was no previous btrbk.conf (rollback removes the file).
        let err = save_config_and_btrbk_conf_with(&cfg, &config_path, &sabotage).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("save failed"), "{msg}");
        assert!(msg.contains("rolling back"), "{msg}");
        assert!(
            msg.contains("config.toml") && msg.contains("btrbk.conf"),
            "{msg}"
        );

        // Case 2: there was one (rollback rewrites it, onto a directory).
        std::fs::remove_dir(&conf_path).unwrap();
        std::fs::write(&conf_path, "previous\n").unwrap();
        let err = save_config_and_btrbk_conf_with(&cfg, &config_path, &sabotage).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("save failed") && msg.contains("rolling back"),
            "{msg}"
        );
    }

    #[test]
    fn an_unreadable_previous_btrbk_conf_refuses_the_edit() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        // A directory where the file belongs: not NotFound, and no text to restore.
        std::fs::create_dir(dir.path().join("btrbk.conf")).unwrap();
        let config_path = dir.path().join("config.toml");
        let err = save_config_and_btrbk_conf(&cfg, &config_path).unwrap_err();
        assert!(err.to_string().contains("rollback copy"), "{err}");
        assert!(!config_path.exists());
    }
}
