//! Rendering of `/etc/btrbk/btrbk.conf` from `config.toml`.
//!
//! Lives in the library, not in `setup/`, because the backup run itself
//! regenerates this file when it adopts or retires a subvolume (`adopt.rs`).

use std::path::Path;

use crate::config::{Config, Retention, Source, SubvolConfig, Target, TargetRole};

pub const GENERATED_HEADER: &str = "\
# Generated by btrdasd setup — do not edit.\n\
# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n";

/// Generate btrbk.conf with global settings, per-source volume blocks (one block
/// per source with all matching targets), and per-subvolume snapshot names.
pub fn render_btrbk_conf(config: &Config) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');

    // Global settings
    out.push_str("# Global settings\n");
    out.push_str("transaction_log         /var/log/btrbk.log\n");
    out.push_str("stream_buffer           256m\n");
    out.push_str("stream_compress         zstd\n");
    out.push_str("lockfile                /var/lock/btrbk.lock\n\n");

    // Source retention
    out.push_str("# Source snapshots — minimal, for send reference\n");
    out.push_str("snapshot_preserve_min   latest\n");
    out.push_str("snapshot_preserve       2d\n\n");

    // Find the primary target to use as the global retention baseline
    let primary = config
        .targets
        .iter()
        .find(|t| t.role == TargetRole::Primary);
    if let Some(p) = primary {
        out.push_str(&format!("# Default target retention (from {})\n", p.label));
        out.push_str("target_preserve_min     latest\n");
        out.push_str(&format!(
            "target_preserve         {}\n\n",
            format_retention(&p.retention)
        ));
    }

    // One volume block per source, with all matching targets inline
    for source in &config.sources {
        let targets = source_targets(config, source);

        if targets.is_empty() {
            continue;
        }

        // Retired entries are not sent; a source left with none has no block.
        let snap_names = resolve_snapshot_names(&source.subvolumes);
        let live: Vec<(&SubvolConfig, &String)> = source
            .subvolumes
            .iter()
            .zip(snap_names.iter())
            .filter(|(sv, _)| sv.retired.is_none())
            .collect();
        if live.is_empty() {
            continue;
        }

        let subdir = source_subdir(source);

        out.push_str(&format!("# {}\n", source.label));
        out.push_str(&format!("volume {}\n", source.volume));
        out.push_str(&format!(
            "  snapshot_dir          {}\n",
            source.snapshot_dir
        ));

        // Emit target lines with per-target retention overrides
        for target in &targets {
            out.push_str(&format!(
                "  target                {}/{}\n",
                target.mount, subdir
            ));
            // If this target's retention differs from primary, emit an override
            if let Some(p) = primary
                && target.label != p.label
                && target.retention != p.retention
            {
                out.push_str(&format!(
                    "    target_preserve     {}\n",
                    format_retention(&target.retention)
                ));
            }
        }
        out.push('\n');

        for (subvol, snap_name) in live {
            out.push_str(&format!("  subvolume             {}\n", subvol.name));
            out.push_str(&format!("    snapshot_name       {snap_name}\n\n"));
        }
    }

    out
}

/// Format a Retention struct into btrbk's preserve format (e.g., "4w 12m 4y").
fn format_retention(r: &Retention) -> String {
    let mut parts = Vec::new();
    if r.daily > 0 {
        parts.push(format!("{}d", r.daily));
    }
    if r.weekly > 0 {
        parts.push(format!("{}w", r.weekly));
    }
    if r.monthly > 0 {
        parts.push(format!("{}m", r.monthly));
    }
    if r.yearly > 0 {
        parts.push(format!("{}y", r.yearly));
    }
    if parts.is_empty() {
        "4w".to_string()
    } else {
        parts.join(" ")
    }
}

/// The snapshot name btrbk would be given for a subvolume with no explicit
/// `snapshot_name`: `@` removed, `/` flattened to `-`, and `root` for the
/// bare top-level subvolume.
pub fn algorithmic_snapshot_name(subvol_name: &str) -> String {
    let stripped = subvol_name.replace('@', "").replace('/', "-");
    if stripped.is_empty() {
        "root".to_string()
    } else {
        stripped
    }
}

/// Resolve snapshot names for a list of subvolumes, using explicit overrides
/// where present and generating safe algorithmic names otherwise.
/// On a collision the colliding names get a `root-` prefix. That does not
/// separate two algorithmic names that both resolve the same way (`@home` and
/// `home` both become `root-home`).
pub fn resolve_snapshot_names(subvols: &[SubvolConfig]) -> Vec<String> {
    use std::collections::HashMap;

    let mut names: Vec<String> = subvols
        .iter()
        .map(|sv| {
            if let Some(ref name) = sv.snapshot_name {
                return name.clone();
            }
            algorithmic_snapshot_name(&sv.name)
        })
        .collect();

    // Detect and resolve collisions by appending the full subvol name
    let mut counts: HashMap<String, usize> = HashMap::new();
    for name in &names {
        *counts.entry(name.clone()).or_insert(0) += 1;
    }

    for (i, name) in names.clone().iter().enumerate() {
        if counts[name] > 1 && subvols[i].snapshot_name.is_none() {
            // Disambiguate: use the full subvol name with @ → "" and special chars → "-"
            let disambiguated = algorithmic_snapshot_name(&subvols[i].name);
            // If still the same, prepend "root-" for the bare @ case
            if disambiguated == *name {
                names[i] = format!("root-{}", subvols[i].name.replace('@', ""));
            } else {
                names[i] = disambiguated;
            }
        }
    }

    names
}

/// Save an edited config and regenerate btrbk.conf from it, or change
/// neither. Every path that edits `config.toml` outside a sync — the CLI's
/// `subvol` commands and every D-Bus helper method that saves — goes through
/// this, so the two files cannot drift apart by that route. An entry that is in config.toml but not in btrbk.conf is not
/// backed up, however it looks.
pub fn save_config_and_btrbk_conf(
    cfg: &Config,
    config_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    save_config_and_btrbk_conf_with(cfg, config_path, &|cfg, path| cfg.save(path))
}

type ConfigSaver<'a> = dyn Fn(&Config, &Path) -> Result<(), Box<dyn std::error::Error>> + 'a;

/// `save_config_and_btrbk_conf` with the config save injectable, so a test can
/// make that step fail in ways a real filesystem will not on demand.
fn save_config_and_btrbk_conf_with(
    cfg: &Config,
    config_path: &Path,
    save: &ConfigSaver<'_>,
) -> Result<(), Box<dyn std::error::Error>> {
    let errors = cfg.validate();
    if !errors.is_empty() {
        return Err(errors.join("\n").into());
    }
    let conf_path = Path::new(&cfg.general.btrbk_conf);
    // Absent is a state to restore (by removing what we write); unreadable is
    // not, because then a failed save could not be undone. Refuse that case.
    let previous = match std::fs::read_to_string(conf_path) {
        Ok(text) => Some(text),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            return Err(format!(
                "cannot read {} to keep a rollback copy: {e}",
                conf_path.display()
            )
            .into());
        }
    };
    crate::fsutil::write_atomic(conf_path, &render_btrbk_conf(cfg))?;
    // Every error here names its own file; the messages add no path.
    if let Err(e) = save(cfg, config_path) {
        let rollback = match &previous {
            Some(text) => crate::fsutil::write_atomic(conf_path, text),
            None => std::fs::remove_file(conf_path).map_err(|re| {
                std::io::Error::new(
                    re.kind(),
                    format!("cannot remove {}: {re}", conf_path.display()),
                )
            }),
        };
        if let Err(re) = rollback {
            return Err(format!(
                "{e}; rolling back also failed: {re} — the two files may disagree"
            )
            .into());
        }
        return Err(e);
    }
    Ok(())
}

/// The targets a source's volume block sends to.
fn source_targets<'a>(config: &'a Config, source: &crate::config::Source) -> Vec<&'a Target> {
    config
        .targets
        .iter()
        .filter(|t| t.role == TargetRole::Primary || t.role == TargetRole::Mirror)
        .filter(|t| source.target_labels.is_empty() || source.target_labels.contains(&t.label))
        .collect()
}

/// The directory under each target a source's snapshots are sent to: the
/// FIRST `target_subdirs` entry, else the source label. Further entries are
/// not used by the renderer.
fn source_subdir(source: &crate::config::Source) -> &str {
    source
        .target_subdirs
        .first()
        .map_or(source.label.as_str(), String::as_str)
}

/// Every `(target, subdirectory)` that `render_btrbk_conf` names in a
/// `target` line — what must exist on a mounted target before btrbk runs.
/// Sources with no live entry render no block and so need no directory.
/// Each pair appears once.
pub fn target_dirs(config: &Config) -> Vec<(&Target, &str)> {
    let mut dirs: Vec<(&Target, &str)> = Vec::new();
    for source in &config.sources {
        if source.subvolumes.iter().all(|sv| sv.retired.is_some()) {
            continue;
        }
        let subdir = source_subdir(source);
        for target in source_targets(config, source) {
            if !dirs
                .iter()
                .any(|(t, d)| t.label == target.label && *d == subdir)
            {
                dirs.push((target, subdir));
            }
        }
    }
    dirs
}

/// One `(subvolume, target)` pair `render_btrbk_conf` declares: a live
/// subvolume of a source, and a target its volume block sends it to.
///
/// btrbk names such a pair by the target's directory and the subvolume's
/// snapshot name, `<target_dir>/<snapshot_name>`, and a command-line filter
/// can say exactly that — which is how a run is limited to some sources AND
/// some targets at once (`backup::btrbk_filters`).
#[derive(Debug, Clone)]
pub struct DeclaredPair<'a> {
    pub source: &'a Source,
    pub subvolume: &'a SubvolConfig,
    /// The name btrbk gives this subvolume's snapshots.
    pub snapshot_name: String,
    pub target: &'a Target,
}

impl DeclaredPair<'_> {
    /// The path of the `target` line this pair is sent under:
    /// `<mount>/<subdirectory>`.
    pub fn target_dir(&self) -> String {
        format!("{}/{}", self.target.mount, source_subdir(self.source))
    }
}

/// Every `(subvolume, target)` pair `render_btrbk_conf` puts in the file, in
/// the order it writes them: per source with a target, per live (not
/// retired) subvolume, per target. A source with no target, or no live
/// subvolume, has no block and so no pair. Derived from the same helpers the
/// renderer uses, and tested against its output, so the two cannot drift.
pub fn declared_pairs(config: &Config) -> Vec<DeclaredPair<'_>> {
    let mut pairs = Vec::new();
    for source in &config.sources {
        let targets = source_targets(config, source);
        let names = resolve_snapshot_names(&source.subvolumes);
        for (subvolume, snapshot_name) in source.subvolumes.iter().zip(names) {
            if subvolume.retired.is_some() {
                continue;
            }
            for target in &targets {
                pairs.push(DeclaredPair {
                    source,
                    subvolume,
                    snapshot_name: snapshot_name.clone(),
                    target,
                });
            }
        }
    }
    pairs
}

/// The `<target dir>/<snapshot name>` of every pair a rendered `btrbk.conf`
/// declares, read back from its text — what the tests compare
/// [`declared_pairs`] and the backup filters against.
#[cfg(test)]
pub(crate) fn pairs_declared_in(text: &str) -> std::collections::BTreeSet<String> {
    let mut declared = std::collections::BTreeSet::new();
    let (mut targets, mut names): (Vec<String>, Vec<String>) = (Vec::new(), Vec::new());
    let mut flush = |targets: &mut Vec<String>, names: &mut Vec<String>| {
        for t in targets.iter() {
            for n in names.iter() {
                declared.insert(format!("{t}/{n}"));
            }
        }
        targets.clear();
        names.clear();
    };
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with("volume ") {
            flush(&mut targets, &mut names);
        } else if let Some(dir) = line.strip_prefix("target ") {
            targets.push(dir.trim().to_string());
        } else if let Some(name) = line.strip_prefix("snapshot_name ") {
            names.push(name.trim().to_string());
        }
    }
    flush(&mut targets, &mut names);
    declared
}

/// Refuse a config, submitted from outside, that moves `general.btrbk_conf`.
/// Saving it writes `btrbk.conf` as root at the path the config names, so a
/// caller-supplied config must not choose where that write lands (the D-Bus
/// helper's polkit check authorizes the action, never the path). Moving the
/// file is a root edit of `config.toml`.
pub fn refuse_moving_btrbk_conf(current: &Config, submitted: &Config) -> Result<(), String> {
    if submitted.general.btrbk_conf == current.general.btrbk_conf {
        return Ok(());
    }
    Err(format!(
        "general.btrbk_conf cannot be changed this way (is '{}', submitted '{}'); edit config.toml as root",
        current.general.btrbk_conf, submitted.general.btrbk_conf
    ))
}

/// [`refuse_moving_btrbk_conf`] against the config currently on disk, which
/// may not load. A `config.toml` that cannot be loaded must still be
/// repairable from the GUI, so the submitted path is then compared with the
/// default (`Config::default()`, `/etc/btrbk/btrbk.conf`) instead of refusing
/// the save outright — still a path fixed in code, never one the caller
/// chooses (bd DAS-Backup-Manager-h4t).
pub fn refuse_moving_btrbk_conf_from<E: std::fmt::Display>(
    current: Result<Config, E>,
    submitted: &Config,
) -> Result<(), String> {
    match current {
        Ok(current) => refuse_moving_btrbk_conf(&current, submitted),
        Err(e) => {
            let default = Config::default().general.btrbk_conf;
            if submitted.general.btrbk_conf == default {
                Ok(())
            } else {
                Err(format!(
                    "the current config cannot be loaded ({e}), so a config submitted to \
                     repair it must keep general.btrbk_conf at the default '{default}' \
                     (submitted '{}'); edit config.toml as root",
                    submitted.general.btrbk_conf
                ))
            }
        }
    }
}

#[cfg(test)]
mod tests {

    #[test]
    fn retired_entries_and_all_retired_sources_are_not_rendered() {
        let mut cfg = test_config();
        cfg.sources[0].subvolumes[0].retired = Some("2026-01-01".into());
        let text = render_btrbk_conf(&cfg);
        let gone = &cfg.sources[0].subvolumes[0].name;
        assert!(
            !text.contains(&format!("subvolume             {gone}\n")),
            "{text}"
        );

        for sv in &mut cfg.sources[0].subvolumes {
            sv.retired = Some("2026-01-01".into());
        }
        let text = render_btrbk_conf(&cfg);
        assert!(
            !text.contains(&format!("# {}\n", cfg.sources[0].label)),
            "{text}"
        );
    }
    use super::*;

    fn test_config() -> Config {
        let mut config = Config::default();
        config.general.install_prefix = "/usr/local".to_string();
        config.sources.push(Source {
            label: "nvme-root".to_string(),
            volume: "/.btrfs-nvme".to_string(),
            subvolumes: vec![
                SubvolConfig {
                    name: "@".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                    ..Default::default()
                },
                SubvolConfig {
                    name: "@home".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                    ..Default::default()
                },
            ],
            device: "/dev/nvme0n1p2".to_string(),
            snapshot_dir: ".btrbk-snapshots".into(),
            target_subdirs: vec!["nvme".into()],
            target_labels: vec![],
        });
        config.targets.push(Target {
            label: "primary-22tb".to_string(),
            serial: "ZXA0LMAE".to_string(),
            serials: vec!["ZXA0LMAE".to_string()],
            mount_uuid: None,
            mount: "/mnt/backup-22tb".to_string(),
            role: TargetRole::Primary,
            retention: Retention {
                weekly: 4,
                monthly: 2,
                daily: 0,
                yearly: 0,
            },
            display_name: String::new(),
        });
        config
    }

    #[test]
    fn algorithmic_snapshot_name_strips_at_and_flattens_slashes() {
        assert_eq!(algorithmic_snapshot_name("@home"), "home");
        assert_eq!(
            algorithmic_snapshot_name("@srv/stremio-web"),
            "srv-stremio-web"
        );
        assert_eq!(
            algorithmic_snapshot_name("bosco-media/video"),
            "bosco-media-video"
        );
        // The bare top-level subvolume has nothing left once '@' is gone.
        assert_eq!(algorithmic_snapshot_name("@"), "root");
    }

    #[test]
    fn render_btrbk_conf_test() {
        let config = test_config();
        let result = render_btrbk_conf(&config);
        // Check volume, subvolume, target, retention, header
        assert!(result.contains("volume /.btrfs-nvme"), "missing volume");
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.trim().ends_with("@")),
            "missing subvolume @"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.contains("@home")),
            "missing subvolume @home"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("target") && l.contains("/mnt/backup-22tb")),
            "missing target /mnt/backup-22tb"
        );
        assert!(result.contains("4w 2m"), "missing retention 4w 2m");
        assert!(
            result.contains("# Generated by btrdasd setup"),
            "missing header"
        );
        // Verify per-source snapshot_dir is used (not hardcoded)
        assert!(
            result.contains("snapshot_dir          .btrbk-snapshots"),
            "missing default snapshot_dir"
        );
    }

    #[test]
    fn render_btrbk_conf_uses_per_source_snapshot_dir() {
        let mut config = test_config();
        // Add a second source with a different snapshot_dir
        config.sources.push(Source {
            label: "hdd-projects".to_string(),
            volume: "/.btrfs-hdd".to_string(),
            subvolumes: vec![SubvolConfig {
                name: "ClaudeCodeProjects".to_string(),
                manual_only: false,
                snapshot_name: None,
                ..Default::default()
            }],
            device: "/dev/sda".to_string(),
            snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".into(),
            target_subdirs: vec![],
            target_labels: vec![],
        });
        let result = render_btrbk_conf(&config);
        // The HDD source must use its custom snapshot_dir, not the default
        assert!(
            result.contains("snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots"),
            "btrbk.conf must use per-source snapshot_dir, got:\n{result}"
        );
    }

    fn subvol(name: &str, snapshot_name: Option<&str>) -> SubvolConfig {
        SubvolConfig {
            name: name.to_string(),
            manual_only: false,
            snapshot_name: snapshot_name.map(str::to_string),
            ..Default::default()
        }
    }

    fn retention(daily: u32, weekly: u32, monthly: u32, yearly: u32) -> Retention {
        Retention {
            weekly,
            monthly,
            daily,
            yearly,
        }
    }

    fn target(label: &str, mount: &str, role: TargetRole, retention: Retention) -> Target {
        Target {
            label: label.to_string(),
            serial: String::new(),
            serials: vec![],
            mount_uuid: None,
            mount: mount.to_string(),
            role,
            retention,
            display_name: String::new(),
        }
    }

    /// The shape of the author's deployment (`.claude/rules/backup.md`
    /// §Targets and Retention): one long-retention primary that receives
    /// everything, two short-retention recovery drives that receive only
    /// system data, a system source that fans out to all three, and a bulk
    /// source scoped to the primary alone.
    fn multi_target_config() -> Config {
        let targets = vec![
            target(
                "primary-22tb",
                "/mnt/backup-22tb",
                TargetRole::Primary,
                retention(7, 4, 12, 1),
            ),
            target(
                "system-recovery-A-2tb",
                "/mnt/backup-system-recovery-A",
                TargetRole::Mirror,
                retention(7, 0, 0, 0),
            ),
            target(
                "system-recovery-B-2tb",
                "/mnt/backup-system-recovery-B",
                TargetRole::Mirror,
                retention(7, 0, 0, 0),
            ),
        ];
        let sources = vec![
            Source {
                label: "nvme".to_string(),
                volume: "/.btrfs-nvme".to_string(),
                subvolumes: vec![
                    subvol("@", None),
                    subvol("@home", None),
                    subvol("@root", None),
                    subvol("@var/log", None),
                ],
                device: "/dev/nvme0n1p2".to_string(),
                snapshot_dir: ".btrbk-snapshots".to_string(),
                target_subdirs: vec!["nvme".to_string()],
                target_labels: vec![],
            },
            Source {
                label: "hdd-projects".to_string(),
                volume: "/.btrfs-hdd".to_string(),
                subvolumes: vec![
                    subvol("ClaudeCodeProjects", None),
                    subvol(
                        "ClaudeCodeProjects/DAS-Backup-Manager",
                        Some("das-backup-manager"),
                    ),
                ],
                device: "/dev/sda".to_string(),
                snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".to_string(),
                target_subdirs: vec![],
                target_labels: vec!["primary-22tb".to_string()],
            },
            Source {
                label: "retired".to_string(),
                volume: "/.btrfs-retired".to_string(),
                subvolumes: vec![subvol("data", None)],
                device: "/dev/sdz".to_string(),
                snapshot_dir: ".btrbk-snapshots".to_string(),
                target_subdirs: vec![],
                target_labels: vec!["no-such-target".to_string()],
            },
        ];
        Config {
            targets,
            sources,
            ..Config::default()
        }
    }

    #[test]
    fn render_btrbk_conf_renders_the_whole_file_for_a_multi_target_config() {
        // Asserted in full because every line is load-bearing: the `target`
        // lines decide which drive a subvolume is sent to, the
        // `target_preserve` lines decide how long it is kept there, and
        // `snapshot_name` is the on-disk identity of each send/receive chain.
        let expected = concat!(
            "# Generated by btrdasd setup — do not edit.\n",
            "# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n",
            "\n",
            "# Global settings\n",
            "transaction_log         /var/log/btrbk.log\n",
            "stream_buffer           256m\n",
            "stream_compress         zstd\n",
            "lockfile                /var/lock/btrbk.lock\n",
            "\n",
            "# Source snapshots — minimal, for send reference\n",
            "snapshot_preserve_min   latest\n",
            "snapshot_preserve       2d\n",
            "\n",
            "# Default target retention (from primary-22tb)\n",
            "target_preserve_min     latest\n",
            "target_preserve         7d 4w 12m 1y\n",
            "\n",
            // target_labels = [] fans out to every target. The primary
            // inherits the global retention; each recovery drive carries its
            // own shorter one as an override.
            "# nvme\n",
            "volume /.btrfs-nvme\n",
            "  snapshot_dir          .btrbk-snapshots\n",
            "  target                /mnt/backup-22tb/nvme\n",
            "  target                /mnt/backup-system-recovery-A/nvme\n",
            "    target_preserve     7d\n",
            "  target                /mnt/backup-system-recovery-B/nvme\n",
            "    target_preserve     7d\n",
            "\n",
            // `@` and `@root` both strip to `root`; btrbk refuses two
            // subvolumes that would write the same snapshot, so both are
            // renamed. `forget::parse_subvol_snapshot_names` and
            // `backup-run.sh` rely on exactly these two names.
            "  subvolume             @\n",
            "    snapshot_name       root-\n",
            "\n",
            "  subvolume             @home\n",
            "    snapshot_name       home\n",
            "\n",
            "  subvolume             @root\n",
            "    snapshot_name       root-root\n",
            "\n",
            "  subvolume             @var/log\n",
            "    snapshot_name       var-log\n",
            "\n",
            // Scoped to the primary: bulk data must never reach the 2 TB
            // recovery drives. No target_subdirs, so the label is the subdir.
            "# hdd-projects\n",
            "volume /.btrfs-hdd\n",
            "  snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots\n",
            "  target                /mnt/backup-22tb/hdd-projects\n",
            "\n",
            "  subvolume             ClaudeCodeProjects\n",
            "    snapshot_name       ClaudeCodeProjects\n",
            "\n",
            "  subvolume             ClaudeCodeProjects/DAS-Backup-Manager\n",
            "    snapshot_name       das-backup-manager\n",
            "\n",
            // "retired" names a target that is not configured, so it gets no
            // volume block at all: a block without a target line would make
            // btrbk snapshot the source and send it nowhere.
        );
        assert_eq!(render_btrbk_conf(&multi_target_config()), expected);
    }

    #[test]
    fn render_btrbk_conf_overrides_retention_only_where_it_differs_from_the_primary() {
        // A mirror with the primary's own retention inherits the global
        // `target_preserve`; repeating it per target would be noise that
        // hides the overrides which do matter.
        let mut config = multi_target_config();
        config.targets[1].retention = config.targets[0].retention.clone();
        let result = render_btrbk_conf(&config);
        assert!(
            result.contains(concat!(
                "  target                /mnt/backup-22tb/nvme\n",
                "  target                /mnt/backup-system-recovery-A/nvme\n",
                "  target                /mnt/backup-system-recovery-B/nvme\n",
                "    target_preserve     7d\n",
                "\n",
            )),
            "{result}"
        );
        assert_eq!(result.matches("    target_preserve     ").count(), 1);
    }

    #[test]
    fn render_btrbk_conf_scopes_a_source_to_a_mirror_alone() {
        // target_labels selects by label, whatever the target's role.
        let mut config = multi_target_config();
        config.sources[0].target_labels = vec!["system-recovery-B-2tb".to_string()];
        let result = render_btrbk_conf(&config);
        assert!(
            result.contains(concat!(
                "volume /.btrfs-nvme\n",
                "  snapshot_dir          .btrbk-snapshots\n",
                "  target                /mnt/backup-system-recovery-B/nvme\n",
                "    target_preserve     7d\n",
                "\n",
            )),
            "{result}"
        );
        assert!(!result.contains("/mnt/backup-22tb/nvme"), "{result}");
        assert!(
            !result.contains("/mnt/backup-system-recovery-A/nvme"),
            "{result}"
        );
    }

    #[test]
    fn format_retention_emits_only_the_non_zero_periods() {
        // A period the config leaves at zero is omitted, in the fixed order
        // daily, weekly, monthly, yearly; 1 is the smallest count that must
        // be rendered. This string is each target's whole retention policy.
        let cases = [
            (retention(7, 4, 12, 1), "7d 4w 12m 1y"),
            (retention(1, 1, 1, 1), "1d 1w 1m 1y"),
            (retention(7, 0, 0, 0), "7d"),
            (retention(0, 4, 0, 0), "4w"),
            (retention(0, 0, 12, 0), "12m"),
            (retention(0, 0, 0, 1), "1y"),
            (retention(1, 0, 0, 0), "1d"),
            (retention(0, 1, 0, 0), "1w"),
            (retention(0, 0, 1, 0), "1m"),
            (retention(0, 4, 2, 0), "4w 2m"),
            (retention(7, 0, 0, 2), "7d 2y"),
            (retention(0, 4, 12, 4), "4w 12m 4y"),
        ];
        for (retention, expected) in cases {
            assert_eq!(format_retention(&retention), expected, "{retention:?}");
        }
    }

    #[test]
    fn format_retention_falls_back_to_four_weeks_when_every_period_is_zero() {
        // An all-zero retention must not leave `target_preserve` without an
        // argument, nor render "0d 0w 0m 0y"; it gets the four-week fallback.
        assert_eq!(format_retention(&retention(0, 0, 0, 0)), "4w");
        assert_eq!(format_retention(&Retention::default()), "4w");
    }

    fn snapshot_names(subvols: &[(&str, Option<&str>)]) -> Vec<String> {
        let subvols: Vec<SubvolConfig> = subvols
            .iter()
            .map(|(name, snapshot_name)| subvol(name, *snapshot_name))
            .collect();
        resolve_snapshot_names(&subvols)
    }

    #[test]
    fn resolve_snapshot_names_leaves_unique_names_alone() {
        // The name is the identity of an existing send/receive chain:
        // renaming a subvolume that collides with nothing would strand every
        // snapshot already taken of it.
        assert_eq!(
            snapshot_names(&[
                ("@", None),
                ("@home", None),
                ("@var/log", None),
                ("ClaudeCodeProjects", None),
                ("Audiobooks", Some("books")),
            ]),
            ["root", "home", "var-log", "ClaudeCodeProjects", "books"]
        );
    }

    #[test]
    fn resolve_snapshot_names_renames_only_the_colliding_subvolumes() {
        // The production case (bd DAS-Backup-Manager-5ig, -ycr): `@` and
        // `@root` both strip to `root`. Their neighbours keep their names.
        assert_eq!(
            snapshot_names(&[
                ("@", None),
                ("@home", None),
                ("@root", None),
                ("@opt", None)
            ]),
            ["root-", "home", "root-root", "opt"]
        );
    }

    #[test]
    fn resolve_snapshot_names_never_rewrites_an_explicit_name() {
        // An explicit snapshot_name is the operator's decision. When it
        // collides with an algorithmic name, the algorithmic one moves.
        assert_eq!(
            snapshot_names(&[("@home", None), ("users", Some("home"))]),
            ["root-home", "home"]
        );
        assert_eq!(
            snapshot_names(&[("users", Some("home")), ("@home", None), ("@opt", None)]),
            ["home", "root-home", "opt"]
        );
    }

    // ---- subvol config editing: config.toml and btrbk.conf change together ----

    fn saveable_config(dir: &Path) -> Config {
        let text = format!(
            r#"[general]
version = "0.7.22"
install_prefix = "/usr"
db_path = "{db}"
btrbk_conf = "{conf}"
[init]
system = "systemd"
[schedule]
incremental = "03:00"
full = "Sun 04:00"
randomized_delay_min = 30
[[source]]
label = "s"
volume = "/vol"
device = "UUID=abc"
[[source.subvolumes]]
name = "@"
[[target]]
label = "t"
serial = "X"
mount = "/mnt/t"
role = "primary"
[target.retention]
daily = 7
[email]
enabled = false
[gui]
enabled = false
"#,
            db = dir.join("index.db").display(),
            conf = dir.join("btrbk.conf").display(),
        );
        Config::from_toml(&text).unwrap()
    }

    #[test]
    fn save_writes_config_and_btrbk_conf_that_agree() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let config_path = dir.path().join("config.toml");
        save_config_and_btrbk_conf(&cfg, &config_path).unwrap();

        let reloaded = Config::load(&config_path).unwrap();
        assert_eq!(reloaded.to_toml().unwrap(), cfg.to_toml().unwrap());
        let conf = std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap();
        assert_eq!(conf, render_btrbk_conf(&reloaded));
    }

    #[test]
    fn save_keeps_the_mode_of_both_files_it_replaces() {
        // The helper's ConfigSet and the CLI's subvol commands come here.
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let config_path = dir.path().join("config.toml");
        let conf_path = dir.path().join("btrbk.conf");
        for (path, mode) in [(&config_path, 0o600), (&conf_path, 0o640)] {
            std::fs::write(path, "old").unwrap();
            std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode)).unwrap();
        }
        save_config_and_btrbk_conf(&cfg, &config_path).unwrap();
        for (path, mode) in [(&config_path, 0o600), (&conf_path, 0o640)] {
            assert_eq!(
                std::fs::metadata(path).unwrap().permissions().mode() & 0o7777,
                mode,
                "{}",
                path.display()
            );
        }
        assert_ne!(std::fs::read_to_string(&conf_path).unwrap(), "old");
    }

    #[test]
    fn save_of_an_invalid_config_writes_neither_file() {
        let dir = tempfile::tempdir().unwrap();
        let mut cfg = saveable_config(dir.path());
        cfg.schedule.incremental = "not a time".into();
        assert!(!cfg.validate().is_empty(), "fixture must be invalid");
        let config_path = dir.path().join("config.toml");
        let err = save_config_and_btrbk_conf(&cfg, &config_path).unwrap_err();
        assert!(!err.to_string().is_empty());
        assert!(!config_path.exists());
        assert!(!dir.path().join("btrbk.conf").exists());
    }

    #[test]
    fn failed_config_save_restores_the_previous_btrbk_conf() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let conf_path = dir.path().join("btrbk.conf");
        std::fs::write(&conf_path, "previous btrbk.conf\n").unwrap();
        // The longest name a file can have: no temp file's name fits beside
        // it, so the config save fails — for root too.
        let config_path = dir.path().join(format!("{}.toml", "x".repeat(250)));

        assert!(save_config_and_btrbk_conf(&cfg, &config_path).is_err());
        assert_eq!(
            std::fs::read_to_string(&conf_path).unwrap(),
            "previous btrbk.conf\n"
        );
        assert!(!config_path.exists());
    }

    #[test]
    fn failed_config_save_leaves_no_btrbk_conf_when_there_was_none() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let config_path = dir.path().join(format!("{}.toml", "x".repeat(250)));

        assert!(save_config_and_btrbk_conf(&cfg, &config_path).is_err());
        assert!(!dir.path().join("btrbk.conf").exists());
    }

    #[test]
    fn a_failed_rollback_is_reported_and_names_both_files() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        let conf_path = dir.path().join("btrbk.conf");
        let config_path = dir.path().join("config.toml");
        // The save fails as `Config::save` does, naming its file, and on the
        // way out leaves a directory where the rollback needs a file: both
        // the restore and the removal fail.
        let sabotage = |_: &Config, path: &Path| -> Result<(), Box<dyn std::error::Error>> {
            std::fs::remove_file(&conf_path).unwrap();
            std::fs::create_dir(&conf_path).unwrap();
            Err(format!("cannot write {}: disk full", path.display()).into())
        };
        let once = |msg: &str| {
            for path in [&config_path, &conf_path] {
                assert_eq!(
                    msg.matches(&path.display().to_string()).count(),
                    1,
                    "{} named once: {msg}",
                    path.display()
                );
            }
        };

        // Case 1: there was no previous btrbk.conf (rollback removes the file).
        let err = save_config_and_btrbk_conf_with(&cfg, &config_path, &sabotage).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.starts_with(&format!(
                "cannot write {}: disk full; ",
                config_path.display()
            )),
            "{msg}"
        );
        assert!(
            msg.contains(&format!(
                "rolling back also failed: cannot remove {}: ",
                conf_path.display()
            )),
            "{msg}"
        );
        once(&msg);

        // Case 2: there was one (rollback rewrites it, onto a directory).
        std::fs::remove_dir(&conf_path).unwrap();
        std::fs::write(&conf_path, "previous\n").unwrap();
        let err = save_config_and_btrbk_conf_with(&cfg, &config_path, &sabotage).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains(&format!(
                "rolling back also failed: cannot write {}: ",
                conf_path.display()
            )),
            "{msg}"
        );
        once(&msg);
    }

    #[test]
    fn an_unreadable_previous_btrbk_conf_refuses_the_edit() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = saveable_config(dir.path());
        // A directory where the file belongs: not NotFound, and no text to restore.
        std::fs::create_dir(dir.path().join("btrbk.conf")).unwrap();
        let config_path = dir.path().join("config.toml");
        let err = save_config_and_btrbk_conf(&cfg, &config_path).unwrap_err();
        assert!(err.to_string().contains("rollback copy"), "{err}");
        assert!(!config_path.exists());
    }

    #[test]
    fn a_submitted_config_may_not_move_btrbk_conf() {
        let current = Config::default();
        assert_eq!(refuse_moving_btrbk_conf(&current, &current.clone()), Ok(()));
        let mut moved = current.clone();
        moved.general.btrbk_conf = "/usr/lib/anything-root-owned".into();
        let err = refuse_moving_btrbk_conf(&current, &moved).unwrap_err();
        assert!(err.contains("anything-root-owned"), "{err}");
    }

    #[test]
    fn a_broken_current_config_can_be_repaired_at_the_default_btrbk_conf_only() {
        let broken: Result<Config, String> = Err("expected `=`".into());
        let submitted = Config::default();
        assert_eq!(submitted.general.btrbk_conf, "/etc/btrbk/btrbk.conf");
        assert_eq!(
            refuse_moving_btrbk_conf_from(broken.clone(), &submitted),
            Ok(()),
            "a repair at the default path is accepted"
        );
        let mut moved = submitted.clone();
        moved.general.btrbk_conf = "/usr/lib/anything-root-owned".into();
        let err = refuse_moving_btrbk_conf_from(broken, &moved).unwrap_err();
        assert!(err.contains("cannot be loaded (expected `=`)"), "{err}");
        assert!(err.contains("anything-root-owned"), "{err}");
        assert!(err.contains("'/etc/btrbk/btrbk.conf'"), "{err}");
    }

    #[test]
    fn a_loadable_current_config_is_compared_as_before() {
        let mut current = Config::default();
        current.general.btrbk_conf = "/srv/btrbk.conf".into();
        let ok: Result<Config, String> = Ok(current.clone());
        assert_eq!(refuse_moving_btrbk_conf_from(ok.clone(), &current), Ok(()));
        // The default path is NOT a free pass while the current config loads.
        let err = refuse_moving_btrbk_conf_from(ok, &Config::default()).unwrap_err();
        assert!(err.contains("is '/srv/btrbk.conf'"), "{err}");
    }

    #[test]
    fn target_dirs_are_exactly_the_target_lines_the_renderer_writes() {
        let mut cfg = test_config();
        // A second source: no subdirs (falls back to its label), sends to
        // the first target only; a third with everything retired.
        let mut extra = cfg.sources[0].clone();
        extra.label = "extra".into();
        extra.target_subdirs = Vec::new();
        extra.target_labels = vec![cfg.targets[0].label.clone()];
        cfg.sources.push(extra);
        let mut gone = cfg.sources[0].clone();
        gone.label = "gone".into();
        gone.target_subdirs = vec!["gone-dir".into(), "unused".into()];
        for sv in &mut gone.subvolumes {
            sv.retired = Some("2026-01-01".into());
        }
        cfg.sources.push(gone);
        cfg.sources[0].target_subdirs.push("second-unused".into());

        let text = render_btrbk_conf(&cfg);
        let rendered: Vec<String> = text
            .lines()
            .filter_map(|l| l.trim().strip_prefix("target "))
            .map(|p| p.trim().to_string())
            .collect::<std::collections::BTreeSet<_>>()
            .into_iter()
            .collect();
        let listed: Vec<String> = target_dirs(&cfg)
            .into_iter()
            .map(|(t, d)| format!("{}/{}", t.mount, d))
            .collect::<std::collections::BTreeSet<_>>()
            .into_iter()
            .collect();
        assert_eq!(listed, rendered);
        assert!(listed.iter().any(|p| p.ends_with("/extra")), "{listed:?}");
        assert!(
            !listed
                .iter()
                .any(|p| p.contains("unused") || p.contains("gone-dir"))
        );
        assert_eq!(
            target_dirs(&cfg).len(),
            listed.len(),
            "each pair once: {:?}",
            target_dirs(&cfg)
                .iter()
                .map(|(t, d)| (&t.label, *d))
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn target_dirs_keeps_one_entry_per_target_and_directory() {
        let mut cfg = test_config();
        let mut second = cfg.targets[0].clone();
        second.label = "second".into();
        second.mount = "/mnt/second".into();
        cfg.targets.push(second);
        // Two sources sharing one subdirectory: one entry per target.
        let mut twin = cfg.sources[0].clone();
        twin.label = "twin".into();
        cfg.sources.push(twin);
        let pairs: Vec<(String, String)> = target_dirs(&cfg)
            .into_iter()
            .map(|(t, d)| (t.label.clone(), d.to_string()))
            .collect();
        let sub = cfg.sources[0].target_subdirs[0].clone();
        assert_eq!(
            pairs,
            vec![
                (cfg.targets[0].label.clone(), sub.clone()),
                ("second".to_string(), sub)
            ]
        );
    }

    // --- declared_pairs: what a command-line filter can name -----------------

    /// Two sources sharing one volume, a third on another, and two targets;
    /// one subvolume retired, one with an explicit snapshot name, one source
    /// scoped to the first target only.
    fn pairs_config() -> Config {
        let mut cfg = test_config();
        let sv = |name: &str| SubvolConfig {
            name: name.into(),
            ..Default::default()
        };
        cfg.sources.clear();
        let source = |label: &str, volume: &str, subvolumes: Vec<SubvolConfig>| Source {
            label: label.into(),
            volume: volume.into(),
            subvolumes,
            device: "/dev/test".into(),
            snapshot_dir: ".btrbk-snapshots".into(),
            target_subdirs: vec![label.into()],
            target_labels: vec![],
        };
        cfg.sources.push(source(
            "s1",
            "/.btrfs-a",
            vec![
                sv("@"),
                SubvolConfig {
                    snapshot_name: Some("home-data".into()),
                    ..sv("@home")
                },
                SubvolConfig {
                    retired: Some("2026-01-01".into()),
                    ..sv("@gone")
                },
            ],
        ));
        let mut s2 = source("s2", "/.btrfs-a", vec![sv("@vm")]);
        s2.target_labels = vec!["primary-22tb".into()];
        cfg.sources.push(s2);
        cfg.sources
            .push(source("s3", "/.btrfs-b", vec![sv("@data")]));
        let mut second = cfg.targets[0].clone();
        second.label = "recovery".into();
        second.mount = "/mnt/recovery".into();
        cfg.targets.push(second);
        cfg
    }

    fn pair_names(cfg: &Config) -> Vec<String> {
        declared_pairs(cfg)
            .iter()
            .map(|p| format!("{}/{}", p.target_dir(), p.snapshot_name))
            .collect()
    }

    #[test]
    fn declared_pairs_are_the_live_subvolumes_times_the_targets_of_their_source() {
        let cfg = pairs_config();
        assert_eq!(
            pair_names(&cfg),
            [
                // s1: `@` (algorithmic `root`) and `@home` (explicit
                // `home-data`) to both targets; `@gone` is retired.
                "/mnt/backup-22tb/s1/root",
                "/mnt/recovery/s1/root",
                "/mnt/backup-22tb/s1/home-data",
                "/mnt/recovery/s1/home-data",
                // s2 is scoped to the primary target only.
                "/mnt/backup-22tb/s2/vm",
                // s3 goes to both.
                "/mnt/backup-22tb/s3/data",
                "/mnt/recovery/s3/data",
            ]
        );
        let pairs = declared_pairs(&cfg);
        assert_eq!(pairs[0].source.label, "s1");
        assert_eq!(pairs[0].subvolume.name, "@");
        assert_eq!(pairs[0].target.label, "primary-22tb");
        assert_eq!(pairs[1].target.label, "recovery");
        assert_eq!(pairs[4].source.label, "s2");
    }

    #[test]
    fn a_source_with_no_target_or_no_live_subvolume_has_no_pair() {
        let mut cfg = pairs_config();
        cfg.sources[2].target_labels = vec!["no-such-target".into()];
        for sv in &mut cfg.sources[1].subvolumes {
            sv.retired = Some("2026-01-01".into());
        }
        let names = pair_names(&cfg);
        assert!(
            !names
                .iter()
                .any(|n| n.contains("/s2/") || n.contains("/s3/")),
            "{names:?}"
        );
        assert_eq!(
            names.len(),
            4,
            "only s1's two live subvolumes x two targets"
        );
    }

    /// The pairs and the file agree: every `<target dir>/<snapshot name>` the
    /// rendered `btrbk.conf` declares is a pair, and every pair is declared.
    /// The filters built from pairs name nothing else, so a drift between the
    /// two would make btrbk answer "does not match any declaration" (exit 2)
    /// or, worse, match something that was not meant.
    #[test]
    fn declared_pairs_are_exactly_what_the_rendered_file_declares() {
        let cfg = pairs_config();
        let text = render_btrbk_conf(&cfg);
        let declared = pairs_declared_in(&text);
        let from_pairs: std::collections::BTreeSet<String> = pair_names(&cfg).into_iter().collect();
        assert_eq!(from_pairs, declared, "{text}");
        assert_eq!(
            pair_names(&cfg).len(),
            declared.len(),
            "no pair is listed twice"
        );
    }
}
