// Template engine — renders config files and scripts from a Config struct.
// Each function builds output strings programmatically (no external template files).

#![allow(dead_code)]

use super::config::*;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERATED_HEADER: &str = "\
# Generated by btrdasd setup — do not edit.\n\
# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n";

// Production scripts embedded in binary (installed to ${prefix}/lib/das-backup/, flat)
const SCRIPT_BACKUP_RUN: &str = include_str!("../../../scripts/backup-run.sh");
const SCRIPT_BACKUP_VERIFY: &str = include_str!("../../../scripts/backup-verify.sh");
const SCRIPT_BOOT_ARCHIVE_CLEANUP: &str = include_str!("../../../scripts/boot-archive-cleanup.sh");

// ---------------------------------------------------------------------------
// Render functions
// ---------------------------------------------------------------------------

/// Generate btrbk.conf with global settings, per-source volume blocks (one block
/// per source with all matching targets), and per-subvolume snapshot names.
pub fn render_btrbk_conf(config: &Config) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');

    // Global settings
    out.push_str("# Global settings\n");
    out.push_str("transaction_log         /var/log/btrbk.log\n");
    out.push_str("stream_buffer           256m\n");
    out.push_str("stream_compress         zstd\n");
    out.push_str("lockfile                /var/lock/btrbk.lock\n\n");

    // Source retention
    out.push_str("# Source snapshots — minimal, for send reference\n");
    out.push_str("snapshot_preserve_min   latest\n");
    out.push_str("snapshot_preserve       2d\n\n");

    // Find the primary target to use as the global retention baseline
    let primary = config
        .targets
        .iter()
        .find(|t| t.role == TargetRole::Primary);
    if let Some(p) = primary {
        out.push_str(&format!("# Default target retention (from {})\n", p.label));
        out.push_str("target_preserve_min     latest\n");
        out.push_str(&format!(
            "target_preserve         {}\n\n",
            format_retention(&p.retention)
        ));
    }

    // One volume block per source, with all matching targets inline
    for source in &config.sources {
        let targets: Vec<&Target> = config
            .targets
            .iter()
            .filter(|t| t.role == TargetRole::Primary || t.role == TargetRole::Mirror)
            .filter(|t| source.target_labels.is_empty() || source.target_labels.contains(&t.label))
            .collect();

        if targets.is_empty() {
            continue;
        }

        // Determine the target subdir for this source
        let subdir = source.target_subdirs.first().unwrap_or(&source.label);

        out.push_str(&format!("# {}\n", source.label));
        out.push_str(&format!("volume {}\n", source.volume));
        out.push_str(&format!(
            "  snapshot_dir          {}\n",
            source.snapshot_dir
        ));

        // Emit target lines with per-target retention overrides
        for target in &targets {
            out.push_str(&format!(
                "  target                {}/{}\n",
                target.mount, subdir
            ));
            // If this target's retention differs from primary, emit an override
            if let Some(p) = primary
                && target.label != p.label
                && target.retention != p.retention
            {
                out.push_str(&format!(
                    "    target_preserve     {}\n",
                    format_retention(&target.retention)
                ));
            }
        }
        out.push('\n');

        // Pre-compute snapshot names and detect collisions
        let snap_names = resolve_snapshot_names(&source.subvolumes);

        for (subvol, snap_name) in source.subvolumes.iter().zip(snap_names.iter()) {
            out.push_str(&format!("  subvolume             {}\n", subvol.name));
            out.push_str(&format!("    snapshot_name       {snap_name}\n\n"));
        }
    }

    out
}

/// Format a Retention struct into btrbk's preserve format (e.g., "4w 12m 4y").
fn format_retention(r: &Retention) -> String {
    let mut parts = Vec::new();
    if r.daily > 0 {
        parts.push(format!("{}d", r.daily));
    }
    if r.weekly > 0 {
        parts.push(format!("{}w", r.weekly));
    }
    if r.monthly > 0 {
        parts.push(format!("{}m", r.monthly));
    }
    if r.yearly > 0 {
        parts.push(format!("{}y", r.yearly));
    }
    if parts.is_empty() {
        "4w".to_string()
    } else {
        parts.join(" ")
    }
}

/// Resolve snapshot names for a list of subvolumes, using explicit overrides
/// where present and generating safe algorithmic names otherwise.
/// Detects collisions and appends suffixes to disambiguate.
fn resolve_snapshot_names(subvols: &[SubvolConfig]) -> Vec<String> {
    use std::collections::HashMap;

    let mut names: Vec<String> = subvols
        .iter()
        .map(|sv| {
            if let Some(ref name) = sv.snapshot_name {
                return name.clone();
            }
            let stripped = sv.name.replace('@', "").replace('/', "-");
            if stripped.is_empty() {
                "root".to_string()
            } else {
                stripped
            }
        })
        .collect();

    // Detect and resolve collisions by appending the full subvol name
    let mut counts: HashMap<String, usize> = HashMap::new();
    for name in &names {
        *counts.entry(name.clone()).or_insert(0) += 1;
    }

    for (i, name) in names.clone().iter().enumerate() {
        if counts[name] > 1 && subvols[i].snapshot_name.is_none() {
            // Disambiguate: use the full subvol name with @ → "" and special chars → "-"
            let full = subvols[i].name.replace('@', "").replace('/', "-");
            let disambiguated = if full.is_empty() {
                "root".to_string()
            } else {
                full
            };
            // If still the same, prepend "root-" for the bare @ case
            if disambiguated == *name {
                names[i] = format!("root-{}", subvols[i].name.replace('@', ""));
            } else {
                names[i] = disambiguated;
            }
        }
    }

    names
}

/// Generate a systemd .service unit file. When `full` is true, appends " --full"
/// to the ExecStart line.
///
/// `TimeoutStartSec=infinity` (not a fixed bound): `backup-run.sh` takes the
/// blocking `/run/das-maintenance.lock` shared with the scrub engine
/// (`indexer/src/scrub.rs`, bd DAS-Backup-Manager-212/atq), so a backup that
/// starts while a scrub pass is running legitimately waits — potentially for
/// hours — before it can proceed. A finite `TimeoutStartSec` would SIGKILL the
/// backup mid-wait. The maintenance lock is the correctness mechanism against
/// overlap, not a timeout (user decision 2026-07-27, bd DAS-Backup-Manager-b6f).
pub fn render_systemd_service(config: &Config, full: bool) -> String {
    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);
    let desc = if full {
        "DAS Backup - Full BTRFS backup"
    } else {
        "DAS Backup - Incremental BTRFS backup"
    };
    let exec_args = if full { " --full" } else { "" };

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description={desc}\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         ExecStart={script_dir}/backup-run.sh{exec_args}\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=infinity\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate a systemd .timer unit file. Converts schedule strings to OnCalendar
/// format: "03:00" becomes "*-*-* 03:00:00", "Sun 04:00" becomes "Sun *-*-* 04:00:00".
pub fn render_systemd_timer(config: &Config, full: bool) -> String {
    let (desc, calendar) = if full {
        (
            "DAS Backup Timer - Weekly full backup",
            &config.schedule.full,
        )
    } else {
        (
            "DAS Backup Timer - Daily incremental backup",
            &config.schedule.incremental,
        )
    };

    // Convert schedule to OnCalendar format
    let on_calendar = if full {
        // "Sun 04:00" -> "Sun *-*-* 04:00:00"
        let parts: Vec<&str> = calendar.split_whitespace().collect();
        if parts.len() == 2 {
            format!("{} *-*-* {}:00", parts[0], parts[1])
        } else {
            format!("*-*-* {}:00", calendar)
        }
    } else {
        // "03:00" -> "*-*-* 03:00:00"
        format!("*-*-* {}:00", calendar)
    };

    let delay_secs = config.schedule.randomized_delay_min * 60;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description={desc}\n\
         \n\
         [Timer]\n\
         OnCalendar={on_calendar}\n\
         RandomizedDelaySec={delay_secs}\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate the das-scrub.service unit file. Deliberately dumb by design
/// (user decision 2026-07-27, bd DAS-Backup-Manager-atq): NO `Conflicts=`
/// (which would stop the other unit — cancellation was explicitly scrapped
/// in favor of deferral), NO `ExecStopPost` cancel, NO `RuntimeMaxSec=`. The
/// scrub engine (`indexer/src/scrub.rs`) itself defers to a running backup
/// via the blocking `/run/das-maintenance.lock` shared with
/// `backup-run.sh`, so a unit-layer mechanism would not cover manual
/// `btrdasd scrub run` invocations anyway. `TimeoutStartSec=infinity`
/// because the pass (and any lock wait ahead of it) is unbounded — a real
/// monthly pass across the DAS filesystems runs many hours.
///
/// `ExecStart` is preceded by a comment documenting the exit-code split
/// (`bd DAS-Backup-Manager-18p`): `btrdasd scrub run` exits 0 whenever the
/// pass ran, even if it found real damage, specifically so this unit never
/// lands in `failed` state for a finding that Sentinel's restart-rate
/// limiter cannot brake (failures 14–18 h apart never trip the 3/600s
/// window). See `exit_code_for_pass` in `indexer/src/main.rs`.
pub fn render_systemd_scrub_service(config: &Config) -> String {
    let prefix = &config.general.install_prefix;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Scheduled BTRFS scrub of backup targets\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         # Exit semantics (bd DAS-Backup-Manager-18p): exit 0 means the pass\n\
         # RAN (findings are reported via email + health, not this exit code);\n\
         # nonzero means the pass could NOT run at all. This keeps a scrub\n\
         # that finds real damage from ever retry-looping under Sentinel.\n\
         ExecStart={prefix}/bin/btrdasd scrub run\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=infinity\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate the das-scrub.timer unit file. `OnCalendar` is consumed verbatim
/// from `config.scrub.on_calendar` (default `*-*-01 05:30:00`, monthly) — see
/// the doc comment on `Scrub::on_calendar` in `indexer/src/config.rs`. NO
/// `RandomizedDelaySec`: the fixed time clears the daily-backup worst case
/// (~04:15) and the Sunday-full worst case (~04:55) with margin, and the
/// maintenance lock — not timing — is the safety net against overlap (user
/// decision 2026-07-27).
pub fn render_systemd_scrub_timer(config: &Config) -> String {
    let on_calendar = &config.scrub.on_calendar;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Monthly BTRFS scrub timer\n\
         \n\
         [Timer]\n\
         OnCalendar={on_calendar}\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate the das-backup-doctor.service unit file. `Type=oneshot`, no
/// `Restart=` (Sentinel — `cachyos-sentinel` — handles retries for a unit
/// that lands in `failed` state; the unit itself stays as clean as
/// `das-backup.service`/`das-scrub.service`, per the project's established
/// convention of leaving retry policy entirely to Sentinel rather than
/// duplicating it in the unit).
///
/// `ExecStart` is preceded by a comment documenting the exit-code split (bd
/// DAS-Backup-Manager-01u, mirroring das-scrub.service's precedent for bd
/// DAS-Backup-Manager-18p): unlike scrub, a drift check genuinely wants exit
/// 1 to mean "drift found" — it is a fast, read-mostly scan with no
/// multi-hour-retry hazard, so there is no reason to hide findings from the
/// exit code the way scrub does.
///
/// `TimeoutStartSec=600` (not `infinity` like das-backup/das-scrub): those
/// units use a *blocking* maintenance-lock acquisition that can legitimately
/// wait hours behind a real backup or scrub pass, so a finite timeout would
/// `SIGKILL` them mid-wait. `btrdasd doctor` deliberately acquires both its
/// locks non-blocking (`doctor::try_acquire_locks`) and defers immediately
/// (exit 0) rather than queuing — so it never has a legitimate reason to run
/// long, and a bound here is a real safety net against a hung `btrfs`
/// subprocess rather than fighting the unit's own design.
pub fn render_systemd_doctor_service(config: &Config) -> String {
    let prefix = &config.general.install_prefix;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Weekly subvolume drift check\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         # Exit semantics (bd DAS-Backup-Manager-01u): 0 = no drift found, or\n\
         # deferred because a backup/scrub/another doctor run holds a lock (never\n\
         # a failure). 1 = the run was not clean — drift found (missing or stale\n\
         # subvolumes), OR at least one configured volume failed to mount/list\n\
         # while others were checked successfully (that volume's subvolumes went\n\
         # unchecked, which is itself a finding this exit code surfaces). Unlike\n\
         # das-scrub.service's exit code, this one is meant to surface findings,\n\
         # because a drift check is a fast read-mostly scan with no multi-hour-\n\
         # retry hazard to protect against. 2 = could not run at all — every\n\
         # configured source volume failed to mount or list, so nothing was ever\n\
         # examined (config load failure and lock I/O errors also land here, via\n\
         # the CLI's own error path rather than this exit-code mapping).\n\
         ExecStart={prefix}/bin/btrdasd doctor --check-drift --email\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=600\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate the das-backup-doctor.timer unit file. Fixed `Sun 02:00` — before
/// the Sunday full backup (04:00) and monthly scrub (05:30 on the 1st), so a
/// drift finding is visible ahead of that week's backup window rather than
/// discovered after the fact. No `RandomizedDelaySec` — like das-scrub.timer,
/// the fixed time is deliberate and the maintenance lock (which this check
/// acquires non-blocking and defers on, never queuing) is the safety net
/// against overlap, not timing.
pub fn render_systemd_doctor_timer(_config: &Config) -> String {
    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Weekly subvolume drift check timer\n\
         \n\
         [Timer]\n\
         OnCalendar=Sun *-*-* 02:00:00\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate cron entries for incremental (daily) and full (weekly) backups.
pub fn render_cron_entry(config: &Config) -> String {
    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);

    // Parse "03:00" -> hour=3, minute=0
    let (inc_hour, inc_min) = parse_time(&config.schedule.incremental);

    // Parse "Sun 04:00" -> dow=0, hour=4, minute=0
    let (full_dow, full_hour, full_min) = parse_schedule_with_day(&config.schedule.full);

    format!(
        "{GENERATED_HEADER}\
         # Incremental backup (daily)\n\
         {inc_min} {inc_hour} * * * root {script_dir}/backup-run.sh \
         >> /var/log/das-backup.log 2>&1\n\
         \n\
         # Full backup (weekly)\n\
         {full_min} {full_hour} * * {full_dow} root {script_dir}/backup-run.sh --full \
         >> /var/log/das-backup.log 2>&1\n"
    )
}

// Email config file generation removed 2026-05-16 — Protonmail Bridge SMTP
// credentials are sourced directly from `~/.config/pbridge.conf` (the single
// canonical source per `~/.claude/rules/infrastructure.md`). Both the bash
// orchestrator (`scripts/backup-run.sh::parse_pbridge_smtp`) and the Rust
// reporter (`indexer/src/report.rs::send_email_report`) read pbridge.conf
// directly — no project-local email config file is generated or installed.

// ESP sync hook generation removed 2026-04-10 — root cause of the 2026-03-05
// incident that wiped the DAS 2TB emergency recovery drives' independent OS
// ESPs. NVMe-pair ESP mirroring is handled by a separate, unrelated mechanism
// (/usr/local/bin/esp-sync.sh + /etc/pacman.d/hooks/esp-mirror.hook) outside
// this project. See .claude/rules/das-esp-safety.md for the full postmortem.

// ---------------------------------------------------------------------------
// GeneratedFiles — aggregates all rendered files
// ---------------------------------------------------------------------------

/// Collection of all generated files as (path, content) pairs.
pub struct GeneratedFiles {
    pub files: Vec<(String, String)>,
}

impl GeneratedFiles {
    /// Generate all operational files from a Config. Includes systemd units OR cron
    /// entries based on init system, plus btrbk.conf, backup-run.sh, email, and ESP hooks.
    pub fn generate(config: &Config) -> Self {
        let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);
        let mut files = Vec::new();

        // btrbk.conf — canonical location is /etc/btrbk/btrbk.conf
        files.push((
            "/etc/btrbk/btrbk.conf".to_string(),
            render_btrbk_conf(config),
        ));

        // Real production scripts (embedded in binary, config-driven via eval),
        // installed flat — matches cmake's install layout (single canonical
        // location per Single Canonical Source, ~/.claude/rules/development-tools.md)
        files.push((
            format!("{script_dir}/backup-run.sh"),
            SCRIPT_BACKUP_RUN.to_string(),
        ));
        files.push((
            format!("{script_dir}/backup-verify.sh"),
            SCRIPT_BACKUP_VERIFY.to_string(),
        ));
        files.push((
            format!("{script_dir}/boot-archive-cleanup.sh"),
            SCRIPT_BOOT_ARCHIVE_CLEANUP.to_string(),
        ));

        // Scheduling: systemd OR cron
        match config.init.system {
            InitSystem::Systemd => {
                files.push((
                    "/etc/systemd/system/das-backup.service".to_string(),
                    render_systemd_service(config, false),
                ));
                files.push((
                    "/etc/systemd/system/das-backup.timer".to_string(),
                    render_systemd_timer(config, false),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-full.service".to_string(),
                    render_systemd_service(config, true),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-full.timer".to_string(),
                    render_systemd_timer(config, true),
                ));

                // Scrub unit + timer always installed; whether the timer is
                // *enabled* is gated on `config.scrub.enabled` in
                // `installer::install()` (the engine ignores `enabled` for
                // manual `btrdasd scrub run` and only warns — the timer is
                // the sole enforcement point, bd DAS-Backup-Manager-atq).
                files.push((
                    "/etc/systemd/system/das-scrub.service".to_string(),
                    render_systemd_scrub_service(config),
                ));
                files.push((
                    "/etc/systemd/system/das-scrub.timer".to_string(),
                    render_systemd_scrub_timer(config),
                ));

                // Doctor unit + timer always installed and always enabled —
                // unlike scrub, there is no config toggle for the drift check
                // (it has no meaningful "disabled" state to gate on: it is a
                // read-mostly scan, not a write operation with resource cost
                // worth opting out of). See `installer::install()`.
                files.push((
                    "/etc/systemd/system/das-backup-doctor.service".to_string(),
                    render_systemd_doctor_service(config),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-doctor.timer".to_string(),
                    render_systemd_doctor_timer(config),
                ));
            }
            InitSystem::Sysvinit | InitSystem::Openrc => {
                files.push((
                    "/etc/cron.d/das-backup".to_string(),
                    render_cron_entry(config),
                ));
            }
        }

        // Email credentials are sourced directly from `~/.config/pbridge.conf`
        // — no project-local email config file is generated. See
        // `~/.claude/rules/infrastructure.md` (Protonmail Bridge section).

        Self { files }
    }

    /// Produce a newline-joined manifest of all generated file paths.
    pub fn manifest_content(&self) -> String {
        self.files
            .iter()
            .map(|(p, _)| p.as_str())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Parse a time string like "03:00" into (hour, minute).
fn parse_time(time_str: &str) -> (u32, u32) {
    let parts: Vec<&str> = time_str.split(':').collect();
    let hour = parts.first().and_then(|s| s.parse().ok()).unwrap_or(3);
    let min = parts.get(1).and_then(|s| s.parse().ok()).unwrap_or(0);
    (hour, min)
}

/// Parse a schedule string like "Sun 04:00" into (day_of_week, hour, minute).
/// Day of week: Sun=0, Mon=1, ..., Sat=6.
fn parse_schedule_with_day(schedule: &str) -> (u32, u32, u32) {
    let parts: Vec<&str> = schedule.split_whitespace().collect();
    if parts.len() == 2 {
        let dow = match parts[0].to_lowercase().as_str() {
            "sun" => 0,
            "mon" => 1,
            "tue" => 2,
            "wed" => 3,
            "thu" => 4,
            "fri" => 5,
            "sat" => 6,
            _ => 0,
        };
        let (hour, min) = parse_time(parts[1]);
        (dow, hour, min)
    } else {
        let (hour, min) = parse_time(parts[0]);
        (0, hour, min) // Default to Sunday
    }
}

// ---------------------------------------------------------------------------
// Tests (TDD — written first, implementation follows)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> Config {
        let mut config = Config::default();
        config.general.install_prefix = "/usr/local".to_string();
        config.sources.push(Source {
            label: "nvme-root".to_string(),
            volume: "/.btrfs-nvme".to_string(),
            subvolumes: vec![
                SubvolConfig {
                    name: "@".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                },
                SubvolConfig {
                    name: "@home".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                },
            ],
            device: "/dev/nvme0n1p2".to_string(),
            snapshot_dir: ".btrbk-snapshots".into(),
            target_subdirs: vec!["nvme".into()],
            target_labels: vec![],
        });
        config.targets.push(Target {
            label: "primary-22tb".to_string(),
            serial: "ZXA0LMAE".to_string(),
            serials: vec!["ZXA0LMAE".to_string()],
            mount_uuid: None,
            mount: "/mnt/backup-22tb".to_string(),
            role: TargetRole::Primary,
            retention: Retention {
                weekly: 4,
                monthly: 2,
                daily: 0,
                yearly: 0,
            },
            display_name: String::new(),
        });
        config
    }

    #[test]
    fn render_btrbk_conf_test() {
        let config = test_config();
        let result = render_btrbk_conf(&config);
        // Check volume, subvolume, target, retention, header
        assert!(result.contains("volume /.btrfs-nvme"), "missing volume");
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.trim().ends_with("@")),
            "missing subvolume @"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.contains("@home")),
            "missing subvolume @home"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("target") && l.contains("/mnt/backup-22tb")),
            "missing target /mnt/backup-22tb"
        );
        assert!(result.contains("4w 2m"), "missing retention 4w 2m");
        assert!(
            result.contains("# Generated by btrdasd setup"),
            "missing header"
        );
        // Verify per-source snapshot_dir is used (not hardcoded)
        assert!(
            result.contains("snapshot_dir          .btrbk-snapshots"),
            "missing default snapshot_dir"
        );
    }

    #[test]
    fn render_btrbk_conf_uses_per_source_snapshot_dir() {
        let mut config = test_config();
        // Add a second source with a different snapshot_dir
        config.sources.push(Source {
            label: "hdd-projects".to_string(),
            volume: "/.btrfs-hdd".to_string(),
            subvolumes: vec![SubvolConfig {
                name: "ClaudeCodeProjects".to_string(),
                manual_only: false,
                snapshot_name: None,
            }],
            device: "/dev/sda".to_string(),
            snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".into(),
            target_subdirs: vec![],
            target_labels: vec![],
        });
        let result = render_btrbk_conf(&config);
        // The HDD source must use its custom snapshot_dir, not the default
        assert!(
            result.contains("snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots"),
            "btrbk.conf must use per-source snapshot_dir, got:\n{result}"
        );
    }

    #[test]
    fn render_systemd_service_test() {
        let config = test_config();
        let result = render_systemd_service(&config, false);
        assert!(result.contains("ExecStart=/usr/local/lib/das-backup/backup-run.sh"));
        assert!(!result.contains("/hddRaid1/"));
        assert!(result.contains("# Generated by btrdasd setup"));
    }

    #[test]
    fn render_systemd_service_timeout_is_unbounded_test() {
        // bd DAS-Backup-Manager-b6f: a backup can defer for hours behind a
        // running scrub pass via the shared maintenance lock, so the unit
        // must never be killed by a finite TimeoutStartSec.
        let config = test_config();
        let incremental = render_systemd_service(&config, false);
        let full = render_systemd_service(&config, true);
        assert!(incremental.contains("TimeoutStartSec=infinity"));
        assert!(full.contains("TimeoutStartSec=infinity"));
        assert!(!incremental.contains("TimeoutStartSec=21600"));
        assert!(!full.contains("TimeoutStartSec=21600"));
    }

    #[test]
    fn render_systemd_timer_test() {
        let config = test_config();
        let result = render_systemd_timer(&config, false);
        assert!(result.contains("OnCalendar=*-*-* 03:00:00"));
        assert!(result.contains("RandomizedDelaySec=1800"));
    }

    #[test]
    fn render_systemd_scrub_service_test() {
        let config = test_config();
        let result = render_systemd_scrub_service(&config);
        assert!(result.contains("Type=oneshot"));
        assert!(result.contains("ExecStart=/usr/local/bin/btrdasd scrub run"));
        assert!(result.contains("TimeoutStartSec=infinity"));
        assert!(result.contains("# Generated by btrdasd setup"));
        // bd DAS-Backup-Manager-18p: the unit documents its own exit-code
        // split so a reader of `systemctl cat das-scrub.service` sees why
        // findings don't fail the unit, without needing to go read the
        // engine source.
        assert!(result.contains("# Exit semantics"));
        assert!(result.contains("bd DAS-Backup-Manager-18p"));
        // Explicitly scrapped by user decision 2026-07-27 — deferral via the
        // maintenance lock replaces unit-layer cancellation.
        assert!(!result.contains("Conflicts="));
        assert!(!result.contains("RuntimeMaxSec="));
        assert!(!result.contains("ExecStopPost"));
    }

    #[test]
    fn render_systemd_scrub_timer_test() {
        let config = test_config();
        let result = render_systemd_scrub_timer(&config);
        assert!(result.contains("OnCalendar=*-*-01 05:30:00"));
        assert!(result.contains("Persistent=true"));
        // Fixed 05:30 clears the daily/full worst cases with margin; the
        // maintenance lock is the safety net, not randomized timing.
        assert!(!result.contains("RandomizedDelaySec"));
    }

    #[test]
    fn render_systemd_scrub_timer_uses_configured_calendar_test() {
        let mut config = test_config();
        config.scrub.on_calendar = "*-*-15 02:00:00".to_string();
        let result = render_systemd_scrub_timer(&config);
        assert!(result.contains("OnCalendar=*-*-15 02:00:00"));
    }

    #[test]
    fn render_systemd_doctor_service_test() {
        let config = test_config();
        let result = render_systemd_doctor_service(&config);
        assert!(result.contains("Type=oneshot"));
        assert!(result.contains("ExecStart=/usr/local/bin/btrdasd doctor --check-drift --email"));
        assert!(result.contains("# Generated by btrdasd setup"));
        // bd DAS-Backup-Manager-01u: the unit documents its own exit-code
        // split, mirroring das-scrub.service's precedent.
        assert!(result.contains("# Exit semantics"));
        assert!(result.contains("bd DAS-Backup-Manager-01u"));
        // Deliberately finite (unlike das-backup/das-scrub's infinity) — the
        // doctor's own lock acquisition is non-blocking, so it never has a
        // legitimate reason to run long.
        assert!(result.contains("TimeoutStartSec=600"));
        assert!(!result.contains("TimeoutStartSec=infinity"));
    }

    #[test]
    fn render_systemd_doctor_timer_test() {
        let config = test_config();
        let result = render_systemd_doctor_timer(&config);
        assert!(result.contains("OnCalendar=Sun *-*-* 02:00:00"));
        assert!(result.contains("Persistent=true"));
        // Fixed Sunday 02:00, ahead of the Sunday full backup (04:00) and
        // monthly scrub (05:30 on the 1st) — no RandomizedDelaySec.
        assert!(!result.contains("RandomizedDelaySec"));
    }

    #[test]
    fn render_cron_entry_test() {
        let config = test_config();
        let result = render_cron_entry(&config);
        assert!(result.contains("0 3 * * *"));
        assert!(result.contains("/usr/local/lib/das-backup/backup-run.sh"));
    }

    #[test]
    fn generated_files_include_embedded_scripts() {
        let config = test_config();
        let generated = GeneratedFiles::generate(&config);
        let manifest = generated.manifest_content();
        assert!(
            manifest.contains("/usr/local/lib/das-backup/backup-run.sh"),
            "missing embedded backup-run.sh at flat path"
        );
        assert!(
            manifest.contains("/usr/local/lib/das-backup/backup-verify.sh"),
            "missing embedded backup-verify.sh at flat path"
        );
        assert!(
            manifest.contains("/usr/local/lib/das-backup/boot-archive-cleanup.sh"),
            "missing embedded boot-archive-cleanup.sh at flat path"
        );
        assert!(
            !manifest.contains("das-backup/scripts/"),
            "scripts/ subdir layout must not reappear — flat layout is canonical"
        );
    }

    #[test]
    fn generated_files_manifest() {
        let config = test_config();
        let generated = GeneratedFiles::generate(&config);
        let manifest = generated.manifest_content();
        assert!(manifest.contains("/etc/btrbk/btrbk.conf"));
        assert!(manifest.contains("backup-run.sh"));
        assert!(manifest.contains("das-backup.service"));
        assert!(manifest.contains("das-backup.timer"));
        assert!(manifest.contains("das-scrub.service"));
        assert!(manifest.contains("das-scrub.timer"));
        assert!(manifest.contains("das-backup-doctor.service"));
        assert!(manifest.contains("das-backup-doctor.timer"));
    }
}
