// Template engine — renders config files and scripts from a Config struct.
// Each function builds output strings programmatically (no external template files).

#![allow(dead_code)]

use super::config::*;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERATED_HEADER: &str = "\
# Generated by btrdasd setup — do not edit.\n\
# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n";

// Production scripts embedded in binary (installed to ${prefix}/lib/das-backup/, flat)
const SCRIPT_BACKUP_RUN: &str = include_str!("../../../scripts/backup-run.sh");
const SCRIPT_BACKUP_VERIFY: &str = include_str!("../../../scripts/backup-verify.sh");
const SCRIPT_BOOT_ARCHIVE_CLEANUP: &str = include_str!("../../../scripts/boot-archive-cleanup.sh");

/// Basenames of the files above — the only generated files whose content is
/// fixed at build time rather than derived from `Config`.
///
/// This distinction is what the installer's staleness guard
/// (bd `DAS-Backup-Manager-2lj`) actually rests on. A binary built before a
/// script edit carries a stale `include_str!` copy, so refusing to overwrite an
/// on-disk script newer than the binary is correct. Every OTHER generated file —
/// `btrbk.conf`, every systemd unit, the cron entry — is rendered from the
/// user's `config.toml` by `render_*`, so its content depends on the config and
/// never on the binary's vintage. Guarding those by binary mtime made config
/// edits inert: a successful upgrade stamps them with `now`, which outlives the
/// binary, so the next upgrade refused to rewrite them
/// (bd `DAS-Backup-Manager-bwt`).
const EMBEDDED_SCRIPTS: [&str; 3] = [
    "backup-run.sh",
    "backup-verify.sh",
    "boot-archive-cleanup.sh",
];

/// True when `path` names one of the [`EMBEDDED_SCRIPTS`], i.e. a file whose
/// content came from `include_str!` and may legitimately be older in the binary
/// than on disk. Matches on the final path component so it holds regardless of
/// the configured `install_prefix`.
pub fn is_embedded_script(path: &str) -> bool {
    let base = path.rsplit('/').next().unwrap_or(path);
    EMBEDDED_SCRIPTS.contains(&base)
}

// ---------------------------------------------------------------------------
// Render functions
// ---------------------------------------------------------------------------

/// Generate btrbk.conf with global settings, per-source volume blocks (one block
/// per source with all matching targets), and per-subvolume snapshot names.
pub fn render_btrbk_conf(config: &Config) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');

    // Global settings
    out.push_str("# Global settings\n");
    out.push_str("transaction_log         /var/log/btrbk.log\n");
    out.push_str("stream_buffer           256m\n");
    out.push_str("stream_compress         zstd\n");
    out.push_str("lockfile                /var/lock/btrbk.lock\n\n");

    // Source retention
    out.push_str("# Source snapshots — minimal, for send reference\n");
    out.push_str("snapshot_preserve_min   latest\n");
    out.push_str("snapshot_preserve       2d\n\n");

    // Find the primary target to use as the global retention baseline
    let primary = config
        .targets
        .iter()
        .find(|t| t.role == TargetRole::Primary);
    if let Some(p) = primary {
        out.push_str(&format!("# Default target retention (from {})\n", p.label));
        out.push_str("target_preserve_min     latest\n");
        out.push_str(&format!(
            "target_preserve         {}\n\n",
            format_retention(&p.retention)
        ));
    }

    // One volume block per source, with all matching targets inline
    for source in &config.sources {
        let targets: Vec<&Target> = config
            .targets
            .iter()
            .filter(|t| t.role == TargetRole::Primary || t.role == TargetRole::Mirror)
            .filter(|t| source.target_labels.is_empty() || source.target_labels.contains(&t.label))
            .collect();

        if targets.is_empty() {
            continue;
        }

        // Determine the target subdir for this source
        let subdir = source.target_subdirs.first().unwrap_or(&source.label);

        out.push_str(&format!("# {}\n", source.label));
        out.push_str(&format!("volume {}\n", source.volume));
        out.push_str(&format!(
            "  snapshot_dir          {}\n",
            source.snapshot_dir
        ));

        // Emit target lines with per-target retention overrides
        for target in &targets {
            out.push_str(&format!(
                "  target                {}/{}\n",
                target.mount, subdir
            ));
            // If this target's retention differs from primary, emit an override
            if let Some(p) = primary
                && target.label != p.label
                && target.retention != p.retention
            {
                out.push_str(&format!(
                    "    target_preserve     {}\n",
                    format_retention(&target.retention)
                ));
            }
        }
        out.push('\n');

        // Pre-compute snapshot names and detect collisions
        let snap_names = resolve_snapshot_names(&source.subvolumes);

        for (subvol, snap_name) in source.subvolumes.iter().zip(snap_names.iter()) {
            out.push_str(&format!("  subvolume             {}\n", subvol.name));
            out.push_str(&format!("    snapshot_name       {snap_name}\n\n"));
        }
    }

    out
}

/// Format a Retention struct into btrbk's preserve format (e.g., "4w 12m 4y").
fn format_retention(r: &Retention) -> String {
    let mut parts = Vec::new();
    if r.daily > 0 {
        parts.push(format!("{}d", r.daily));
    }
    if r.weekly > 0 {
        parts.push(format!("{}w", r.weekly));
    }
    if r.monthly > 0 {
        parts.push(format!("{}m", r.monthly));
    }
    if r.yearly > 0 {
        parts.push(format!("{}y", r.yearly));
    }
    if parts.is_empty() {
        "4w".to_string()
    } else {
        parts.join(" ")
    }
}

/// Resolve snapshot names for a list of subvolumes, using explicit overrides
/// where present and generating safe algorithmic names otherwise.
/// On a collision the colliding names get a `root-` prefix. That does not
/// separate two algorithmic names that both resolve the same way (`@home` and
/// `home` both become `root-home`).
fn resolve_snapshot_names(subvols: &[SubvolConfig]) -> Vec<String> {
    use std::collections::HashMap;

    let mut names: Vec<String> = subvols
        .iter()
        .map(|sv| {
            if let Some(ref name) = sv.snapshot_name {
                return name.clone();
            }
            let stripped = sv.name.replace('@', "").replace('/', "-");
            if stripped.is_empty() {
                "root".to_string()
            } else {
                stripped
            }
        })
        .collect();

    // Detect and resolve collisions by appending the full subvol name
    let mut counts: HashMap<String, usize> = HashMap::new();
    for name in &names {
        *counts.entry(name.clone()).or_insert(0) += 1;
    }

    for (i, name) in names.clone().iter().enumerate() {
        if counts[name] > 1 && subvols[i].snapshot_name.is_none() {
            // Disambiguate: use the full subvol name with @ → "" and special chars → "-"
            let full = subvols[i].name.replace('@', "").replace('/', "-");
            let disambiguated = if full.is_empty() {
                "root".to_string()
            } else {
                full
            };
            // If still the same, prepend "root-" for the bare @ case
            if disambiguated == *name {
                names[i] = format!("root-{}", subvols[i].name.replace('@', ""));
            } else {
                names[i] = disambiguated;
            }
        }
    }

    names
}

/// Generate a systemd .service unit file. When `full` is true, appends " --full"
/// to the ExecStart line.
///
/// `TimeoutStartSec=infinity` (not a fixed bound): `backup-run.sh` takes the
/// blocking `/run/das-maintenance.lock` shared with the scrub engine
/// (`indexer/src/scrub.rs`, bd DAS-Backup-Manager-212/atq), so a backup that
/// starts while a scrub pass is running legitimately waits — potentially for
/// hours — before it can proceed. A finite `TimeoutStartSec` would SIGKILL the
/// backup mid-wait. The maintenance lock is the correctness mechanism against
/// overlap, not a timeout (user decision 2026-07-27, bd DAS-Backup-Manager-b6f).
pub fn render_systemd_service(config: &Config, full: bool) -> String {
    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);
    let desc = if full {
        "DAS Backup - Full BTRFS backup"
    } else {
        "DAS Backup - Incremental BTRFS backup"
    };
    let exec_args = if full { " --full" } else { "" };

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description={desc}\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         ExecStart={script_dir}/backup-run.sh{exec_args}\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=infinity\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate a systemd .timer unit file. Converts schedule strings to OnCalendar
/// format: "03:00" becomes "*-*-* 03:00:00", "Sun 04:00" becomes "Sun *-*-* 04:00:00".
pub fn render_systemd_timer(config: &Config, full: bool) -> String {
    let (desc, calendar) = if full {
        (
            "DAS Backup Timer - Weekly full backup",
            &config.schedule.full,
        )
    } else {
        (
            "DAS Backup Timer - Daily incremental backup",
            &config.schedule.incremental,
        )
    };

    // Convert schedule to OnCalendar format
    let on_calendar = if full {
        // "Sun 04:00" -> "Sun *-*-* 04:00:00"
        let parts: Vec<&str> = calendar.split_whitespace().collect();
        if parts.len() == 2 {
            format!("{} *-*-* {}:00", parts[0], parts[1])
        } else {
            format!("*-*-* {}:00", calendar)
        }
    } else {
        // "03:00" -> "*-*-* 03:00:00"
        format!("*-*-* {}:00", calendar)
    };

    let delay_secs = config.schedule.randomized_delay_min * 60;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description={desc}\n\
         \n\
         [Timer]\n\
         OnCalendar={on_calendar}\n\
         RandomizedDelaySec={delay_secs}\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate the das-scrub.service unit file. Deliberately dumb by design
/// (user decision 2026-07-27, bd DAS-Backup-Manager-atq): NO `Conflicts=`
/// (which would stop the other unit — cancellation was explicitly scrapped
/// in favor of deferral), NO `ExecStopPost` cancel, NO `RuntimeMaxSec=`. The
/// scrub engine (`indexer/src/scrub.rs`) itself defers to a running backup
/// via the blocking `/run/das-maintenance.lock` shared with
/// `backup-run.sh`, so a unit-layer mechanism would not cover manual
/// `btrdasd scrub run` invocations anyway. `TimeoutStartSec=infinity`
/// because the pass (and any lock wait ahead of it) is unbounded — a real
/// monthly pass across the DAS filesystems runs many hours.
///
/// `ExecStart` is preceded by a comment documenting the exit-code split
/// (`bd DAS-Backup-Manager-18p`): `btrdasd scrub run` exits 0 whenever the
/// pass ran, even if it found real damage, specifically so this unit never
/// lands in `failed` state for a finding that Sentinel's restart-rate
/// limiter cannot brake (failures 14–18 h apart never trip the 3/600s
/// window). See `exit_code_for_pass` in `indexer/src/main.rs`.
pub fn render_systemd_scrub_service(config: &Config) -> String {
    let prefix = &config.general.install_prefix;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Scheduled BTRFS scrub of backup targets\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         # Exit semantics (bd DAS-Backup-Manager-18p): exit 0 means the pass\n\
         # RAN (findings are reported via email + health, not this exit code);\n\
         # nonzero means the pass could NOT run at all. This keeps a scrub\n\
         # that finds real damage from ever retry-looping under Sentinel.\n\
         ExecStart={prefix}/bin/btrdasd scrub run\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=infinity\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate the das-scrub.timer unit file. `OnCalendar` is consumed verbatim
/// from `config.scrub.on_calendar` (default `*-*-01 03:05:00`, monthly) — see
/// the doc comment on `default_scrub_on_calendar()` in `indexer/src/config.rs`.
/// The 03:05 default is deliberately five minutes AFTER the 03:00 daily backup
/// fires: the backup already holds /run/das-maintenance.lock, so the scrub
/// engine's blocking acquire starts the scrub the moment the backup finishes
/// — "scrub follows the backup on the 1st" (user decision 2026-08-02,
/// superseding the fixed-05:30 gap design of 2026-07-27). The same blocking
/// flock covers overrun in the other direction: a scrub still running when
/// the next day's 03:00 backup fires HOLDS that backup until the scrub
/// completes — deferral, never a skip. When the 1st is a Sunday, the 04:00
/// full backup likewise defers behind the running scrub. NO
/// `RandomizedDelaySec`: the maintenance lock — not timing — is the
/// serialization mechanism.
pub fn render_systemd_scrub_timer(config: &Config) -> String {
    let on_calendar = &config.scrub.on_calendar;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Monthly BTRFS scrub timer\n\
         \n\
         [Timer]\n\
         OnCalendar={on_calendar}\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate the das-backup-doctor.service unit file. `Type=oneshot`, no
/// `Restart=` (Sentinel — `cachyos-sentinel` — handles retries for a unit
/// that lands in `failed` state; the unit itself stays as clean as
/// `das-backup.service`/`das-scrub.service`, per the project's established
/// convention of leaving retry policy entirely to Sentinel rather than
/// duplicating it in the unit).
///
/// `ExecStart` is preceded by a comment documenting the exit-code split (bd
/// DAS-Backup-Manager-01u, mirroring das-scrub.service's precedent for bd
/// DAS-Backup-Manager-18p): unlike scrub, a drift check genuinely wants exit
/// 1 to mean "drift found" — it is a fast, read-mostly scan with no
/// multi-hour-retry hazard, so there is no reason to hide findings from the
/// exit code the way scrub does.
///
/// `TimeoutStartSec=600` (not `infinity` like das-backup/das-scrub): those
/// units use a *blocking* maintenance-lock acquisition that can legitimately
/// wait hours behind a real backup or scrub pass, so a finite timeout would
/// `SIGKILL` them mid-wait. `btrdasd doctor` deliberately acquires both its
/// locks non-blocking (`doctor::try_acquire_locks`) and defers immediately
/// (exit 0) rather than queuing — so it never has a legitimate reason to run
/// long, and a bound here is a real safety net against a hung `btrfs`
/// subprocess rather than fighting the unit's own design.
pub fn render_systemd_doctor_service(config: &Config) -> String {
    let prefix = &config.general.install_prefix;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Weekly subvolume drift check\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         # Exit semantics (bd DAS-Backup-Manager-01u, refined by -f6p):\n\
         #   0 = ran clean, or deferred because a backup/scrub/another doctor run\n\
         #       holds a lock (never a failure).\n\
         #   1 = DRIFT FOUND — missing or stale subvolumes. A successful check\n\
         #       WITH A RESULT, not a malfunction, which is why SuccessExitStatus\n\
         #       below tells systemd not to fail the unit for it. The finding\n\
         #       travels by email (--email) and by the journal report.\n\
         #   3 = at least one configured volume failed to mount/list while others\n\
         #       were checked — those subvolumes went unexamined. An operational\n\
         #       fault, so the unit DOES fail. Outranks 1 when both occur: an\n\
         #       incomplete check cannot claim its drift list is complete.\n\
         #   2 = could not run at all — every configured source volume failed to\n\
         #       mount or list, so nothing was ever examined (config load failure\n\
         #       and lock I/O errors also land here, via the CLI's own error path\n\
         #       rather than this exit-code mapping).\n\
         #\n\
         # Without SuccessExitStatus=1 systemd cannot tell a finding from a\n\
         # malfunction: it marked this unit `failed` on drift, cachyos-sentinel\n\
         # then restarted it and notified 'backup service das-backup-doctor\n\
         # .service last run failed', so the operator was told the checker broke\n\
         # at the moment it worked — an alert that contradicted the drift email\n\
         # carrying the real signal (observed 2026-08-31 13:47).\n\
         SuccessExitStatus=1\n\
         ExecStart={prefix}/bin/btrdasd doctor --check-drift --email\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=600\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate the das-backup-doctor.timer unit file. Fixed `Sun 02:00` — before
/// the Sunday full backup (04:00) and monthly scrub (03:05 on the 1st), so a
/// drift finding is visible ahead of that week's backup window rather than
/// discovered after the fact. No `RandomizedDelaySec` — like das-scrub.timer,
/// the fixed time is deliberate and the maintenance lock (which this check
/// acquires non-blocking and defers on, never queuing) is the safety net
/// against overlap, not timing.
pub fn render_systemd_doctor_timer(_config: &Config) -> String {
    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description=DAS Backup - Weekly subvolume drift check timer\n\
         \n\
         [Timer]\n\
         OnCalendar=Sun *-*-* 02:00:00\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate cron entries for incremental (daily) and full (weekly) backups.
pub fn render_cron_entry(config: &Config) -> Result<String, String> {
    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);

    // Parse "03:00" -> hour=3, minute=0
    let (inc_hour, inc_min) = parse_time(&config.schedule.incremental)?;

    // Parse "Sun 04:00" -> dow=0, hour=4, minute=0
    let (full_dow, full_hour, full_min) = parse_schedule_with_day(&config.schedule.full)?;

    Ok(format!(
        "{GENERATED_HEADER}\
         # Incremental backup (daily)\n\
         {inc_min} {inc_hour} * * * root {script_dir}/backup-run.sh \
         >> /var/log/das-backup.log 2>&1\n\
         \n\
         # Full backup (weekly)\n\
         {full_min} {full_hour} * * {full_dow} root {script_dir}/backup-run.sh --full \
         >> /var/log/das-backup.log 2>&1\n"
    ))
}

// Email config file generation removed 2026-05-16, and there is nothing to
// bring back: since the 2026-08-06 relay migration this project holds no mail
// credential at all. Reports are submitted unauthenticated to the local relay
// at `[email].smtp_host:smtp_port`, which authenticates upstream by envelope
// sender using a key readable only by root. Both senders
// (`scripts/backup-run.sh::send_report` and
// `indexer/src/report.rs::send_email_report`) take their coordinates from
// `[email]` in config.toml — no project-local email config file exists.

// ESP sync hook generation removed 2026-04-10 — root cause of the 2026-03-05
// incident that wiped the DAS 2TB emergency recovery drives' independent OS
// ESPs. NVMe-pair ESP mirroring is handled by a separate, unrelated mechanism
// (/usr/local/bin/esp-sync.sh + /etc/pacman.d/hooks/esp-mirror.hook) outside
// this project. See .claude/rules/esp-safety.md for the full postmortem.

/// Where the udisks-ignore rule is installed.
pub const UDEV_UDISKS_IGNORE_RULES: &str = "/etc/udev/rules.d/99-das-backup-udisks-ignore.rules";

/// True when `value` can be interpolated into a udev `=="..."` match without
/// changing what the rule means: no quote to end the string early, and none
/// of udev's glob characters (`*?[]|`) to widen the match.
pub fn is_udev_safe_value(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
}

/// Generate the udev rule that hides every backup target from udisks2, and so
/// from desktop automounters (bd `DAS-Backup-Manager-a10`, `-xqo`).
///
/// A target left visible is mounted read-write under `/run/media/<user>` at
/// login — a second door onto a filesystem only `backup-run.sh` and `btrdasd`
/// are meant to open. A multi-device target is worse: btrfs reports one member
/// as the mount source, udisks believes the others are still unmounted, and
/// each further login mounts them again.
///
/// Keyed on each configured drive serial, scoped to the btrfs partition so a
/// recovery drive's own ESP is not matched, and additionally on `mount_uuid`
/// where one is configured, which covers a replacement leg whose serial has
/// not reached the config yet. A hand-written predecessor was keyed on the
/// UUID alone and matched nothing for months after the filesystem was
/// re-created; rendering from `config.toml` ties this rule to the identifiers
/// the backup itself mounts by, so it cannot drift from them unnoticed.
pub fn render_udev_udisks_ignore(config: &Config) -> String {
    let mut out = format!(
        "{GENERATED_HEADER}#\n\
         # Hides the backup targets from udisks2 so no desktop session automounts them.\n\
         # Verify with: sudo btrdasd setup --check\n"
    );
    for target in &config.targets {
        out.push_str(&format!("\n# {}\n", target.label.replace('\n', " ")));
        for serial in target.effective_serials() {
            if is_udev_safe_value(&serial) {
                out.push_str(&format!(
                    "SUBSYSTEM==\"block\", ENV{{ID_SERIAL_SHORT}}==\"{serial}\", \
                     ENV{{ID_FS_TYPE}}==\"btrfs\", ENV{{UDISKS_IGNORE}}=\"1\"\n"
                ));
            } else {
                out.push_str("# SKIPPED a serial that is not safe to place in a udev match\n");
            }
        }
        if let Some(uuid) = &target.mount_uuid {
            if is_udev_safe_value(uuid) {
                out.push_str(&format!(
                    "SUBSYSTEM==\"block\", ENV{{ID_FS_UUID}}==\"{uuid}\", \
                     ENV{{UDISKS_IGNORE}}=\"1\"\n"
                ));
            } else {
                out.push_str("# SKIPPED a mount_uuid that is not safe to place in a udev match\n");
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// GeneratedFiles — aggregates all rendered files
// ---------------------------------------------------------------------------

/// Collection of all generated files as (path, content) pairs.
pub struct GeneratedFiles {
    pub files: Vec<(String, String)>,
}

impl GeneratedFiles {
    /// Generate all operational files from a Config. Includes systemd units OR cron
    /// entries based on init system, plus btrbk.conf, the backup scripts and the udisks-ignore
    /// udev rule. No email config and no ESP hook is generated.
    pub fn generate(config: &Config) -> Self {
        let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);
        let mut files = Vec::new();

        // btrbk.conf — canonical location is /etc/btrbk/btrbk.conf
        files.push((
            "/etc/btrbk/btrbk.conf".to_string(),
            render_btrbk_conf(config),
        ));

        // Real production scripts (embedded in binary, config-driven via eval),
        // installed flat — matches cmake's install layout (single canonical
        // location per Single Canonical Source, ~/.claude/rules/development-tools.md)
        files.push((
            format!("{script_dir}/backup-run.sh"),
            SCRIPT_BACKUP_RUN.to_string(),
        ));
        files.push((
            format!("{script_dir}/backup-verify.sh"),
            SCRIPT_BACKUP_VERIFY.to_string(),
        ));
        files.push((
            format!("{script_dir}/boot-archive-cleanup.sh"),
            SCRIPT_BOOT_ARCHIVE_CLEANUP.to_string(),
        ));

        // Scheduling: systemd OR cron
        match config.init.system {
            InitSystem::Systemd => {
                files.push((
                    "/etc/systemd/system/das-backup.service".to_string(),
                    render_systemd_service(config, false),
                ));
                files.push((
                    "/etc/systemd/system/das-backup.timer".to_string(),
                    render_systemd_timer(config, false),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-full.service".to_string(),
                    render_systemd_service(config, true),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-full.timer".to_string(),
                    render_systemd_timer(config, true),
                ));

                // Scrub unit + timer always installed; whether the timer is
                // *enabled* is gated on `config.scrub.enabled` in
                // `installer::install()` (the engine ignores `enabled` for
                // manual `btrdasd scrub run` and only warns — the timer is
                // the sole enforcement point, bd DAS-Backup-Manager-atq).
                files.push((
                    "/etc/systemd/system/das-scrub.service".to_string(),
                    render_systemd_scrub_service(config),
                ));
                files.push((
                    "/etc/systemd/system/das-scrub.timer".to_string(),
                    render_systemd_scrub_timer(config),
                ));

                // Doctor unit + timer always installed and always enabled —
                // unlike scrub, there is no config toggle for the drift check
                // (it has no meaningful "disabled" state to gate on: it is a
                // read-mostly scan, not a write operation with resource cost
                // worth opting out of). See `installer::install()`.
                files.push((
                    "/etc/systemd/system/das-backup-doctor.service".to_string(),
                    render_systemd_doctor_service(config),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-doctor.timer".to_string(),
                    render_systemd_doctor_timer(config),
                ));
            }
            InitSystem::Sysvinit | InitSystem::Openrc => {
                // Fail closed: an unparsable schedule yields NO cron file
                // rather than one silently pinned to 03:00 Sunday. Unreachable
                // via the normal flow — `Config::validate()` rejects a bad
                // schedule before setup ever generates anything
                // (bd DAS-Backup-Manager-06p).
                match render_cron_entry(config) {
                    Ok(entry) => files.push(("/etc/cron.d/das-backup".to_string(), entry)),
                    Err(e) => eprintln!(
                        "Refusing to generate /etc/cron.d/das-backup — {e}. \
                         Fix [schedule] in config.toml and re-run setup."
                    ),
                }
            }
        }

        // Hide the targets from udisks2. Independent of the init system.
        files.push((
            UDEV_UDISKS_IGNORE_RULES.to_string(),
            render_udev_udisks_ignore(config),
        ));

        // No email config file is generated: this project stores no mail
        // credential. See the note above `render_cron_entry`'s neighbours and
        // `.claude/rules/backup.md` §Email Reports.

        Self { files }
    }

    /// Produce a newline-joined manifest of all generated file paths.
    pub fn manifest_content(&self) -> String {
        self.files
            .iter()
            .map(|(p, _)| p.as_str())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Tests (TDD — written first, implementation follows)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> Config {
        let mut config = Config::default();
        config.general.install_prefix = "/usr/local".to_string();
        config.sources.push(Source {
            label: "nvme-root".to_string(),
            volume: "/.btrfs-nvme".to_string(),
            subvolumes: vec![
                SubvolConfig {
                    name: "@".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                },
                SubvolConfig {
                    name: "@home".to_string(),
                    manual_only: false,
                    snapshot_name: None,
                },
            ],
            device: "/dev/nvme0n1p2".to_string(),
            snapshot_dir: ".btrbk-snapshots".into(),
            target_subdirs: vec!["nvme".into()],
            target_labels: vec![],
        });
        config.targets.push(Target {
            label: "primary-22tb".to_string(),
            serial: "ZXA0LMAE".to_string(),
            serials: vec!["ZXA0LMAE".to_string()],
            mount_uuid: None,
            mount: "/mnt/backup-22tb".to_string(),
            role: TargetRole::Primary,
            retention: Retention {
                weekly: 4,
                monthly: 2,
                daily: 0,
                yearly: 0,
            },
            display_name: String::new(),
        });
        config
    }

    #[test]
    fn render_btrbk_conf_test() {
        let config = test_config();
        let result = render_btrbk_conf(&config);
        // Check volume, subvolume, target, retention, header
        assert!(result.contains("volume /.btrfs-nvme"), "missing volume");
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.trim().ends_with("@")),
            "missing subvolume @"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.contains("@home")),
            "missing subvolume @home"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("target") && l.contains("/mnt/backup-22tb")),
            "missing target /mnt/backup-22tb"
        );
        assert!(result.contains("4w 2m"), "missing retention 4w 2m");
        assert!(
            result.contains("# Generated by btrdasd setup"),
            "missing header"
        );
        // Verify per-source snapshot_dir is used (not hardcoded)
        assert!(
            result.contains("snapshot_dir          .btrbk-snapshots"),
            "missing default snapshot_dir"
        );
    }

    #[test]
    fn render_btrbk_conf_uses_per_source_snapshot_dir() {
        let mut config = test_config();
        // Add a second source with a different snapshot_dir
        config.sources.push(Source {
            label: "hdd-projects".to_string(),
            volume: "/.btrfs-hdd".to_string(),
            subvolumes: vec![SubvolConfig {
                name: "ClaudeCodeProjects".to_string(),
                manual_only: false,
                snapshot_name: None,
            }],
            device: "/dev/sda".to_string(),
            snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".into(),
            target_subdirs: vec![],
            target_labels: vec![],
        });
        let result = render_btrbk_conf(&config);
        // The HDD source must use its custom snapshot_dir, not the default
        assert!(
            result.contains("snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots"),
            "btrbk.conf must use per-source snapshot_dir, got:\n{result}"
        );
    }

    fn subvol(name: &str, snapshot_name: Option<&str>) -> SubvolConfig {
        SubvolConfig {
            name: name.to_string(),
            manual_only: false,
            snapshot_name: snapshot_name.map(str::to_string),
        }
    }

    fn retention(daily: u32, weekly: u32, monthly: u32, yearly: u32) -> Retention {
        Retention {
            weekly,
            monthly,
            daily,
            yearly,
        }
    }

    fn target(label: &str, mount: &str, role: TargetRole, retention: Retention) -> Target {
        Target {
            label: label.to_string(),
            serial: String::new(),
            serials: vec![],
            mount_uuid: None,
            mount: mount.to_string(),
            role,
            retention,
            display_name: String::new(),
        }
    }

    /// The shape of the author's deployment (`.claude/rules/backup.md`
    /// §Targets and Retention): one long-retention primary that receives
    /// everything, two short-retention recovery drives that receive only
    /// system data, a system source that fans out to all three, and a bulk
    /// source scoped to the primary alone.
    fn multi_target_config() -> Config {
        let targets = vec![
            target(
                "primary-22tb",
                "/mnt/backup-22tb",
                TargetRole::Primary,
                retention(7, 4, 12, 1),
            ),
            target(
                "system-recovery-A-2tb",
                "/mnt/backup-system-recovery-A",
                TargetRole::Mirror,
                retention(7, 0, 0, 0),
            ),
            target(
                "system-recovery-B-2tb",
                "/mnt/backup-system-recovery-B",
                TargetRole::Mirror,
                retention(7, 0, 0, 0),
            ),
        ];
        let sources = vec![
            Source {
                label: "nvme".to_string(),
                volume: "/.btrfs-nvme".to_string(),
                subvolumes: vec![
                    subvol("@", None),
                    subvol("@home", None),
                    subvol("@root", None),
                    subvol("@var/log", None),
                ],
                device: "/dev/nvme0n1p2".to_string(),
                snapshot_dir: ".btrbk-snapshots".to_string(),
                target_subdirs: vec!["nvme".to_string()],
                target_labels: vec![],
            },
            Source {
                label: "hdd-projects".to_string(),
                volume: "/.btrfs-hdd".to_string(),
                subvolumes: vec![
                    subvol("ClaudeCodeProjects", None),
                    subvol(
                        "ClaudeCodeProjects/DAS-Backup-Manager",
                        Some("das-backup-manager"),
                    ),
                ],
                device: "/dev/sda".to_string(),
                snapshot_dir: "ClaudeCodeProjects/.btrbk-snapshots".to_string(),
                target_subdirs: vec![],
                target_labels: vec!["primary-22tb".to_string()],
            },
            Source {
                label: "retired".to_string(),
                volume: "/.btrfs-retired".to_string(),
                subvolumes: vec![subvol("data", None)],
                device: "/dev/sdz".to_string(),
                snapshot_dir: ".btrbk-snapshots".to_string(),
                target_subdirs: vec![],
                target_labels: vec!["no-such-target".to_string()],
            },
        ];
        Config {
            targets,
            sources,
            ..Config::default()
        }
    }

    #[test]
    fn render_btrbk_conf_renders_the_whole_file_for_a_multi_target_config() {
        // Asserted in full because every line is load-bearing: the `target`
        // lines decide which drive a subvolume is sent to, the
        // `target_preserve` lines decide how long it is kept there, and
        // `snapshot_name` is the on-disk identity of each send/receive chain.
        let expected = concat!(
            "# Generated by btrdasd setup — do not edit.\n",
            "# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n",
            "\n",
            "# Global settings\n",
            "transaction_log         /var/log/btrbk.log\n",
            "stream_buffer           256m\n",
            "stream_compress         zstd\n",
            "lockfile                /var/lock/btrbk.lock\n",
            "\n",
            "# Source snapshots — minimal, for send reference\n",
            "snapshot_preserve_min   latest\n",
            "snapshot_preserve       2d\n",
            "\n",
            "# Default target retention (from primary-22tb)\n",
            "target_preserve_min     latest\n",
            "target_preserve         7d 4w 12m 1y\n",
            "\n",
            // target_labels = [] fans out to every target. The primary
            // inherits the global retention; each recovery drive carries its
            // own shorter one as an override.
            "# nvme\n",
            "volume /.btrfs-nvme\n",
            "  snapshot_dir          .btrbk-snapshots\n",
            "  target                /mnt/backup-22tb/nvme\n",
            "  target                /mnt/backup-system-recovery-A/nvme\n",
            "    target_preserve     7d\n",
            "  target                /mnt/backup-system-recovery-B/nvme\n",
            "    target_preserve     7d\n",
            "\n",
            // `@` and `@root` both strip to `root`; btrbk refuses two
            // subvolumes that would write the same snapshot, so both are
            // renamed. `forget::parse_subvol_snapshot_names` and
            // `backup-run.sh` rely on exactly these two names.
            "  subvolume             @\n",
            "    snapshot_name       root-\n",
            "\n",
            "  subvolume             @home\n",
            "    snapshot_name       home\n",
            "\n",
            "  subvolume             @root\n",
            "    snapshot_name       root-root\n",
            "\n",
            "  subvolume             @var/log\n",
            "    snapshot_name       var-log\n",
            "\n",
            // Scoped to the primary: bulk data must never reach the 2 TB
            // recovery drives. No target_subdirs, so the label is the subdir.
            "# hdd-projects\n",
            "volume /.btrfs-hdd\n",
            "  snapshot_dir          ClaudeCodeProjects/.btrbk-snapshots\n",
            "  target                /mnt/backup-22tb/hdd-projects\n",
            "\n",
            "  subvolume             ClaudeCodeProjects\n",
            "    snapshot_name       ClaudeCodeProjects\n",
            "\n",
            "  subvolume             ClaudeCodeProjects/DAS-Backup-Manager\n",
            "    snapshot_name       das-backup-manager\n",
            "\n",
            // "retired" names a target that is not configured, so it gets no
            // volume block at all: a block without a target line would make
            // btrbk snapshot the source and send it nowhere.
        );
        assert_eq!(render_btrbk_conf(&multi_target_config()), expected);
    }

    #[test]
    fn render_btrbk_conf_overrides_retention_only_where_it_differs_from_the_primary() {
        // A mirror with the primary's own retention inherits the global
        // `target_preserve`; repeating it per target would be noise that
        // hides the overrides which do matter.
        let mut config = multi_target_config();
        config.targets[1].retention = config.targets[0].retention.clone();
        let result = render_btrbk_conf(&config);
        assert!(
            result.contains(concat!(
                "  target                /mnt/backup-22tb/nvme\n",
                "  target                /mnt/backup-system-recovery-A/nvme\n",
                "  target                /mnt/backup-system-recovery-B/nvme\n",
                "    target_preserve     7d\n",
                "\n",
            )),
            "{result}"
        );
        assert_eq!(result.matches("    target_preserve     ").count(), 1);
    }

    #[test]
    fn render_btrbk_conf_scopes_a_source_to_a_mirror_alone() {
        // target_labels selects by label, whatever the target's role.
        let mut config = multi_target_config();
        config.sources[0].target_labels = vec!["system-recovery-B-2tb".to_string()];
        let result = render_btrbk_conf(&config);
        assert!(
            result.contains(concat!(
                "volume /.btrfs-nvme\n",
                "  snapshot_dir          .btrbk-snapshots\n",
                "  target                /mnt/backup-system-recovery-B/nvme\n",
                "    target_preserve     7d\n",
                "\n",
            )),
            "{result}"
        );
        assert!(!result.contains("/mnt/backup-22tb/nvme"), "{result}");
        assert!(
            !result.contains("/mnt/backup-system-recovery-A/nvme"),
            "{result}"
        );
    }

    #[test]
    fn format_retention_emits_only_the_non_zero_periods() {
        // A period the config leaves at zero is omitted, in the fixed order
        // daily, weekly, monthly, yearly; 1 is the smallest count that must
        // be rendered. This string is each target's whole retention policy.
        let cases = [
            (retention(7, 4, 12, 1), "7d 4w 12m 1y"),
            (retention(1, 1, 1, 1), "1d 1w 1m 1y"),
            (retention(7, 0, 0, 0), "7d"),
            (retention(0, 4, 0, 0), "4w"),
            (retention(0, 0, 12, 0), "12m"),
            (retention(0, 0, 0, 1), "1y"),
            (retention(1, 0, 0, 0), "1d"),
            (retention(0, 1, 0, 0), "1w"),
            (retention(0, 0, 1, 0), "1m"),
            (retention(0, 4, 2, 0), "4w 2m"),
            (retention(7, 0, 0, 2), "7d 2y"),
            (retention(0, 4, 12, 4), "4w 12m 4y"),
        ];
        for (retention, expected) in cases {
            assert_eq!(format_retention(&retention), expected, "{retention:?}");
        }
    }

    #[test]
    fn format_retention_falls_back_to_four_weeks_when_every_period_is_zero() {
        // An all-zero retention must not leave `target_preserve` without an
        // argument, nor render "0d 0w 0m 0y"; it gets the four-week fallback.
        assert_eq!(format_retention(&retention(0, 0, 0, 0)), "4w");
        assert_eq!(format_retention(&Retention::default()), "4w");
    }

    fn snapshot_names(subvols: &[(&str, Option<&str>)]) -> Vec<String> {
        let subvols: Vec<SubvolConfig> = subvols
            .iter()
            .map(|(name, snapshot_name)| subvol(name, *snapshot_name))
            .collect();
        resolve_snapshot_names(&subvols)
    }

    #[test]
    fn resolve_snapshot_names_leaves_unique_names_alone() {
        // The name is the identity of an existing send/receive chain:
        // renaming a subvolume that collides with nothing would strand every
        // snapshot already taken of it.
        assert_eq!(
            snapshot_names(&[
                ("@", None),
                ("@home", None),
                ("@var/log", None),
                ("ClaudeCodeProjects", None),
                ("Audiobooks", Some("books")),
            ]),
            ["root", "home", "var-log", "ClaudeCodeProjects", "books"]
        );
    }

    #[test]
    fn resolve_snapshot_names_renames_only_the_colliding_subvolumes() {
        // The production case (bd DAS-Backup-Manager-5ig, -ycr): `@` and
        // `@root` both strip to `root`. Their neighbours keep their names.
        assert_eq!(
            snapshot_names(&[
                ("@", None),
                ("@home", None),
                ("@root", None),
                ("@opt", None)
            ]),
            ["root-", "home", "root-root", "opt"]
        );
    }

    #[test]
    fn resolve_snapshot_names_never_rewrites_an_explicit_name() {
        // An explicit snapshot_name is the operator's decision. When it
        // collides with an algorithmic name, the algorithmic one moves.
        assert_eq!(
            snapshot_names(&[("@home", None), ("users", Some("home"))]),
            ["root-home", "home"]
        );
        assert_eq!(
            snapshot_names(&[("users", Some("home")), ("@home", None), ("@opt", None)]),
            ["home", "root-home", "opt"]
        );
    }

    #[test]
    fn render_systemd_service_full_unit_test() {
        let config = test_config();
        assert_eq!(
            render_systemd_service(&config, true),
            concat!(
                "# Generated by btrdasd setup — do not edit.\n",
                "# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n",
                "\n",
                "[Unit]\n",
                "Description=DAS Backup - Full BTRFS backup\n",
                "After=local-fs.target\n",
                "\n",
                "[Service]\n",
                "Type=oneshot\n",
                "ExecStart=/usr/local/lib/das-backup/backup-run.sh --full\n",
                "StandardOutput=journal\n",
                "StandardError=journal\n",
                "Nice=19\n",
                "IOSchedulingClass=idle\n",
                "TimeoutStartSec=infinity\n",
                "\n",
                "[Install]\n",
                "WantedBy=multi-user.target\n",
            )
        );
    }

    #[test]
    fn render_systemd_timer_full_puts_the_weekday_ahead_of_the_date() {
        // systemd's OnCalendar grammar is `DayOfWeek Date Time`. "Sun 04:00"
        // from config.toml has to become "Sun *-*-* 04:00:00"; the weekday
        // anywhere else is rejected by systemd and the weekly full backup
        // never fires.
        let config = test_config();
        assert_eq!(config.schedule.full, "Sun 04:00");
        assert_eq!(
            render_systemd_timer(&config, true),
            concat!(
                "# Generated by btrdasd setup — do not edit.\n",
                "# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n",
                "\n",
                "[Unit]\n",
                "Description=DAS Backup Timer - Weekly full backup\n",
                "\n",
                "[Timer]\n",
                "OnCalendar=Sun *-*-* 04:00:00\n",
                "RandomizedDelaySec=1800\n",
                "Persistent=true\n",
                "WakeSystem=false\n",
                "\n",
                "[Install]\n",
                "WantedBy=timers.target\n",
            )
        );
    }

    #[test]
    fn render_systemd_timer_full_without_a_weekday_fires_daily_at_that_time() {
        let mut config = test_config();
        config.schedule.full = "04:30".to_string();
        let result = render_systemd_timer(&config, true);
        assert!(result.contains("\nOnCalendar=*-*-* 04:30:00\n"), "{result}");
    }

    #[test]
    fn render_systemd_service_test() {
        let config = test_config();
        let result = render_systemd_service(&config, false);
        assert!(result.contains("ExecStart=/usr/local/lib/das-backup/backup-run.sh"));
        assert!(!result.contains("/hddRaid1/"));
        assert!(result.contains("# Generated by btrdasd setup"));
    }

    #[test]
    fn render_systemd_service_timeout_is_unbounded_test() {
        // bd DAS-Backup-Manager-b6f: a backup can defer for hours behind a
        // running scrub pass via the shared maintenance lock, so the unit
        // must never be killed by a finite TimeoutStartSec.
        let config = test_config();
        let incremental = render_systemd_service(&config, false);
        let full = render_systemd_service(&config, true);
        assert!(incremental.contains("TimeoutStartSec=infinity"));
        assert!(full.contains("TimeoutStartSec=infinity"));
        assert!(!incremental.contains("TimeoutStartSec=21600"));
        assert!(!full.contains("TimeoutStartSec=21600"));
    }

    #[test]
    fn render_systemd_timer_test() {
        let config = test_config();
        let result = render_systemd_timer(&config, false);
        assert!(result.contains("OnCalendar=*-*-* 03:00:00"));
        assert!(result.contains("RandomizedDelaySec=1800"));
    }

    #[test]
    fn render_systemd_scrub_service_test() {
        let config = test_config();
        let result = render_systemd_scrub_service(&config);
        assert!(result.contains("Type=oneshot"));
        assert!(result.contains("ExecStart=/usr/local/bin/btrdasd scrub run"));
        assert!(result.contains("TimeoutStartSec=infinity"));
        assert!(result.contains("# Generated by btrdasd setup"));
        // bd DAS-Backup-Manager-18p: the unit documents its own exit-code
        // split so a reader of `systemctl cat das-scrub.service` sees why
        // findings don't fail the unit, without needing to go read the
        // engine source.
        assert!(result.contains("# Exit semantics"));
        assert!(result.contains("bd DAS-Backup-Manager-18p"));
        // Explicitly scrapped by user decision 2026-07-27 — deferral via the
        // maintenance lock replaces unit-layer cancellation.
        assert!(!result.contains("Conflicts="));
        assert!(!result.contains("RuntimeMaxSec="));
        assert!(!result.contains("ExecStopPost"));
    }

    #[test]
    fn render_systemd_scrub_timer_test() {
        let config = test_config();
        let result = render_systemd_scrub_timer(&config);
        assert!(result.contains("OnCalendar=*-*-01 03:05:00"));
        assert!(result.contains("Persistent=true"));
        // 03:05 deliberately trails the 03:00 backup so the maintenance lock
        // serializes scrub-after-backup; the lock, not randomized timing, is
        // the mechanism.
        assert!(!result.contains("RandomizedDelaySec"));
    }

    #[test]
    fn render_systemd_scrub_timer_uses_configured_calendar_test() {
        let mut config = test_config();
        config.scrub.on_calendar = "*-*-15 02:00:00".to_string();
        let result = render_systemd_scrub_timer(&config);
        assert!(result.contains("OnCalendar=*-*-15 02:00:00"));
    }

    #[test]
    fn render_systemd_doctor_service_test() {
        let config = test_config();
        let result = render_systemd_doctor_service(&config);
        assert!(result.contains("Type=oneshot"));
        assert!(result.contains("ExecStart=/usr/local/bin/btrdasd doctor --check-drift --email"));
        assert!(result.contains("# Generated by btrdasd setup"));
        // bd DAS-Backup-Manager-01u: the unit documents its own exit-code
        // split, mirroring das-scrub.service's precedent.
        assert!(result.contains("# Exit semantics"));
        assert!(result.contains("bd DAS-Backup-Manager-01u"));
        // Deliberately finite (unlike das-backup/das-scrub's infinity) — the
        // doctor's own lock acquisition is non-blocking, so it never has a
        // legitimate reason to run long.
        assert!(result.contains("TimeoutStartSec=600"));
        assert!(!result.contains("TimeoutStartSec=infinity"));
    }

    #[test]
    fn render_systemd_doctor_timer_test() {
        let config = test_config();
        let result = render_systemd_doctor_timer(&config);
        assert!(result.contains("OnCalendar=Sun *-*-* 02:00:00"));
        assert!(result.contains("Persistent=true"));
        // Fixed Sunday 02:00, ahead of the Sunday full backup (04:00) and
        // monthly scrub (05:30 on the 1st) — no RandomizedDelaySec.
        assert!(!result.contains("RandomizedDelaySec"));
    }

    #[test]
    fn render_cron_entry_test() {
        let config = test_config();
        let result = render_cron_entry(&config).expect("valid schedule renders");
        assert!(result.contains("0 3 * * *"));
        assert!(result.contains("/usr/local/lib/das-backup/backup-run.sh"));
    }

    // Counter-tests for bd DAS-Backup-Manager-06p. Each of these produced a
    // silently-defaulted cron entry before the parsers returned Result:
    // "3 AM" became 03:00, and "Friday 04:00" became SUNDAY 04:00.
    #[test]
    fn render_cron_entry_refuses_an_unparsable_time() {
        let mut config = test_config();
        config.schedule.incremental = "3 AM".into();
        let err = render_cron_entry(&config).expect_err("must not silently default to 03:00");
        assert!(err.contains("3 AM"), "{err}");
    }

    #[test]
    fn render_cron_entry_refuses_a_full_weekday_name() {
        let mut config = test_config();
        config.schedule.full = "Friday 04:00".into();
        let err = render_cron_entry(&config).expect_err("must not silently default to Sunday");
        assert!(err.contains("friday"), "{err}");
    }

    #[test]
    fn schedule_errors_are_surfaced_by_config_validate() {
        let mut config = test_config();
        config.schedule.incremental = "0300".into();
        config.schedule.full = "Funday 04:00".into();
        let errors = config.validate();
        assert!(
            errors.iter().any(|e| e.contains("schedule.incremental")),
            "{errors:?}"
        );
        assert!(
            errors.iter().any(|e| e.contains("schedule.full")),
            "{errors:?}"
        );
    }

    #[test]
    fn generated_files_include_embedded_scripts() {
        let config = test_config();
        let generated = GeneratedFiles::generate(&config);
        let manifest = generated.manifest_content();
        assert!(
            manifest.contains("/usr/local/lib/das-backup/backup-run.sh"),
            "missing embedded backup-run.sh at flat path"
        );
        assert!(
            manifest.contains("/usr/local/lib/das-backup/backup-verify.sh"),
            "missing embedded backup-verify.sh at flat path"
        );
        assert!(
            manifest.contains("/usr/local/lib/das-backup/boot-archive-cleanup.sh"),
            "missing embedded boot-archive-cleanup.sh at flat path"
        );
        assert!(
            !manifest.contains("das-backup/scripts/"),
            "scripts/ subdir layout must not reappear — flat layout is canonical"
        );
    }

    #[test]
    fn generated_files_manifest() {
        let config = test_config();
        let generated = GeneratedFiles::generate(&config);
        let manifest = generated.manifest_content();
        assert!(manifest.contains("/etc/btrbk/btrbk.conf"));
        assert!(manifest.contains("backup-run.sh"));
        assert!(manifest.contains("das-backup.service"));
        assert!(manifest.contains("das-backup.timer"));
        assert!(manifest.contains("das-scrub.service"));
        assert!(manifest.contains("das-scrub.timer"));
        assert!(manifest.contains("das-backup-doctor.service"));
        assert!(manifest.contains("das-backup-doctor.timer"));
        assert!(manifest.contains(UDEV_UDISKS_IGNORE_RULES));
    }

    /// `test_config()` plus a RAID-1 target that carries a `mount_uuid`.
    fn config_with_uuid_target() -> Config {
        let mut config = test_config();
        config.targets.push(Target {
            label: "pair".to_string(),
            serial: "ZXA1NYGZ".to_string(),
            serials: vec!["ZXA1NYGZ".to_string(), "ZXA1R71M".to_string()],
            mount_uuid: Some("b2dbe07d-40b9-422e-8ccf-ef4931c40457".to_string()),
            mount: "/mnt/pair".to_string(),
            role: TargetRole::Primary,
            retention: Retention {
                weekly: 0,
                monthly: 0,
                daily: 7,
                yearly: 0,
            },
            display_name: String::new(),
        });
        config
    }

    #[test]
    fn render_udev_udisks_ignore_keys_every_target_serial_and_uuid() {
        // bd DAS-Backup-Manager-xqo: one line per configured serial (scoped to
        // the btrfs partition, so a recovery drive's own ESP is not matched),
        // plus one per configured filesystem UUID.
        let result = render_udev_udisks_ignore(&config_with_uuid_target());
        assert!(result.contains("# Generated by btrdasd setup"));
        for serial in ["ZXA0LMAE", "ZXA1NYGZ", "ZXA1R71M"] {
            let line = format!(
                "SUBSYSTEM==\"block\", ENV{{ID_SERIAL_SHORT}}==\"{serial}\", \
                 ENV{{ID_FS_TYPE}}==\"btrfs\", ENV{{UDISKS_IGNORE}}=\"1\"\n"
            );
            assert!(
                result.contains(&line),
                "missing serial rule for {serial}:\n{result}"
            );
        }
        assert!(result.contains(
            "SUBSYSTEM==\"block\", ENV{ID_FS_UUID}==\"b2dbe07d-40b9-422e-8ccf-ef4931c40457\", \
             ENV{UDISKS_IGNORE}=\"1\"\n"
        ));
        // Three serials + one UUID: exactly four rules, nothing invented for
        // the target that has no mount_uuid.
        assert_eq!(result.matches("ENV{UDISKS_IGNORE}=\"1\"").count(), 4);
    }

    #[test]
    fn render_udev_udisks_ignore_refuses_values_that_would_break_rule_syntax() {
        // A serial or UUID is interpolated into a udev match string. One
        // containing a quote would end the string early and turn the rest of
        // the line into rule syntax, so it gets a comment, never a rule.
        let mut config = test_config();
        config.targets[0].serials = vec!["BAD\", ENV{X}==\"".to_string()];
        config.targets[0].mount_uuid = Some("not a uuid\"".to_string());
        let result = render_udev_udisks_ignore(&config);
        assert_eq!(result.matches("ENV{UDISKS_IGNORE}=\"1\"").count(), 0);
        assert!(!result.contains("BAD"));
        assert_eq!(result.matches("# SKIPPED").count(), 2);
    }

    #[test]
    fn udev_safe_value_accepts_serials_and_uuids_only() {
        assert!(is_udev_safe_value("ZK208Q77"));
        assert!(is_udev_safe_value("b2dbe07d-40b9-422e-8ccf-ef4931c40457"));
        assert!(is_udev_safe_value("WD-WX12_A.3"));
        assert!(!is_udev_safe_value(""));
        assert!(!is_udev_safe_value("a\"b"));
        assert!(!is_udev_safe_value("a b"));
        assert!(!is_udev_safe_value("a*"));
        assert!(!is_udev_safe_value("a|b"));
    }

    #[test]
    fn generated_files_carry_the_udev_rule_under_every_init_system() {
        // udisks does not care which init system is running.
        for system in [
            InitSystem::Systemd,
            InitSystem::Sysvinit,
            InitSystem::Openrc,
        ] {
            let mut config = test_config();
            config.init.system = system;
            let generated = GeneratedFiles::generate(&config);
            let rule = generated
                .files
                .iter()
                .find(|(p, _)| p == UDEV_UDISKS_IGNORE_RULES)
                .map(|(_, c)| c.as_str());
            assert_eq!(rule, Some(render_udev_udisks_ignore(&config).as_str()));
        }
    }
}
