// Template engine — renders config files and scripts from a Config struct.
// Each function builds output strings programmatically (no external template files).

#![allow(dead_code)]

use super::config::*;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERATED_HEADER: &str = "\
# Generated by btrdasd setup — do not edit.\n\
# Modify /etc/das-backup/config.toml and run: sudo btrdasd setup --upgrade\n";

// Production scripts embedded in binary (installed to ${prefix}/lib/das-backup/scripts/)
const SCRIPT_BACKUP_RUN: &str = include_str!("../../../scripts/backup-run.sh");
const SCRIPT_BACKUP_VERIFY: &str = include_str!("../../../scripts/backup-verify.sh");
const SCRIPT_BOOT_ARCHIVE_CLEANUP: &str =
    include_str!("../../../scripts/boot-archive-cleanup.sh");

// ---------------------------------------------------------------------------
// Render functions
// ---------------------------------------------------------------------------

/// Generate btrbk.conf with global settings, source retention, and per-source
/// volume blocks with target retention and subvolumes.
pub fn render_btrbk_conf(config: &Config) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push('\n');

    // Global settings
    out.push_str("# Global settings\n");
    out.push_str("transaction_log         /var/log/btrbk.log\n");
    out.push_str("stream_buffer           256m\n");
    out.push_str("stream_compress         zstd\n");
    out.push_str("lockfile                /var/lock/btrbk.lock\n\n");

    // Source retention
    out.push_str("# Source snapshots — minimal, for send reference\n");
    out.push_str("snapshot_preserve_min   latest\n");
    out.push_str("snapshot_preserve       2d\n\n");

    // Per-source volume blocks
    for source in &config.sources {
        // Find targets that are primary or mirror (not esp-sync)
        let targets: Vec<&Target> = config
            .targets
            .iter()
            .filter(|t| t.role == TargetRole::Primary || t.role == TargetRole::Mirror)
            .collect();

        for target in &targets {
            out.push_str(&format!("# {} -> {}\n", source.label, target.label));
            out.push_str(&format!(
                "target_preserve_min     latest\n\
                 target_preserve         {}w {}m\n\n",
                target.retention.weekly, target.retention.monthly
            ));
            out.push_str(&format!("volume {}\n", source.volume));
            out.push_str("  snapshot_dir          .btrbk-snapshots\n");
            out.push_str(&format!(
                "  target                {}/{}\n\n",
                target.mount, source.label
            ));

            for subvol in &source.subvolumes {
                out.push_str(&format!("  subvolume             {subvol}\n"));
                // Generate a safe snapshot name from subvolume
                let snap_name = subvol.replace('@', "").replace('/', "-");
                let snap_name = if snap_name.is_empty() {
                    "root"
                } else {
                    &snap_name
                };
                out.push_str(&format!("    snapshot_name       {snap_name}\n\n"));
            }
        }
    }

    out
}

/// Generate a systemd .service unit file. When `full` is true, appends " --full"
/// to the ExecStart line.
pub fn render_systemd_service(config: &Config, full: bool) -> String {
    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);
    let desc = if full {
        "DAS Backup - Full BTRFS backup"
    } else {
        "DAS Backup - Incremental BTRFS backup"
    };
    let exec_args = if full { " --full" } else { "" };

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description={desc}\n\
         After=local-fs.target\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         ExecStart={script_dir}/backup-run.sh{exec_args}\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         Nice=19\n\
         IOSchedulingClass=idle\n\
         TimeoutStartSec=21600\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n"
    )
}

/// Generate a systemd .timer unit file. Converts schedule strings to OnCalendar
/// format: "03:00" becomes "*-*-* 03:00:00", "Sun 04:00" becomes "Sun *-*-* 04:00:00".
pub fn render_systemd_timer(config: &Config, full: bool) -> String {
    let (desc, calendar) = if full {
        (
            "DAS Backup Timer - Weekly full backup",
            &config.schedule.full,
        )
    } else {
        (
            "DAS Backup Timer - Daily incremental backup",
            &config.schedule.incremental,
        )
    };

    // Convert schedule to OnCalendar format
    let on_calendar = if full {
        // "Sun 04:00" -> "Sun *-*-* 04:00:00"
        let parts: Vec<&str> = calendar.split_whitespace().collect();
        if parts.len() == 2 {
            format!("{} *-*-* {}:00", parts[0], parts[1])
        } else {
            format!("*-*-* {}:00", calendar)
        }
    } else {
        // "03:00" -> "*-*-* 03:00:00"
        format!("*-*-* {}:00", calendar)
    };

    let delay_secs = config.schedule.randomized_delay_min * 60;

    format!(
        "{GENERATED_HEADER}\n\
         [Unit]\n\
         Description={desc}\n\
         \n\
         [Timer]\n\
         OnCalendar={on_calendar}\n\
         RandomizedDelaySec={delay_secs}\n\
         Persistent=true\n\
         WakeSystem=false\n\
         \n\
         [Install]\n\
         WantedBy=timers.target\n"
    )
}

/// Generate cron entries for incremental (daily) and full (weekly) backups.
pub fn render_cron_entry(config: &Config) -> String {
    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);

    // Parse "03:00" -> hour=3, minute=0
    let (inc_hour, inc_min) = parse_time(&config.schedule.incremental);

    // Parse "Sun 04:00" -> dow=0, hour=4, minute=0
    let (full_dow, full_hour, full_min) = parse_schedule_with_day(&config.schedule.full);

    format!(
        "{GENERATED_HEADER}\
         # Incremental backup (daily)\n\
         {inc_min} {inc_hour} * * * root {script_dir}/backup-run.sh \
         >> /var/log/das-backup.log 2>&1\n\
         \n\
         # Full backup (weekly)\n\
         {full_min} {full_hour} * * {full_dow} root {script_dir}/backup-run.sh --full \
         >> /var/log/das-backup.log 2>&1\n"
    )
}

/// Generate the backup-run.sh wrapper script. This is a thin wrapper that execs
/// the real production script installed at ${prefix}/lib/das-backup/scripts/.
/// The real script sources config via `eval "$(btrdasd config dump-env)"`.
pub fn render_backup_run(config: &Config) -> String {
    let script_dir = format!("{}/lib/das-backup/scripts", config.general.install_prefix);
    format!(
        "#!/usr/bin/env zsh\n\
         {GENERATED_HEADER}\
         exec \"{script_dir}/backup-run.sh\" \"$@\"\n"
    )
}

/// Generate SMTP email configuration file. Returns empty string if email is disabled.
pub fn render_email_conf(config: &Config) -> String {
    if !config.email.enabled {
        return String::new();
    }

    let auth = match config.email.auth {
        AuthMethod::Plain | AuthMethod::Starttls => "on",
        AuthMethod::None => "off",
    };
    let tls = match config.email.auth {
        AuthMethod::Starttls => "on",
        _ => "off",
    };

    format!(
        "{GENERATED_HEADER}\
         SMTP_HOST=\"{}\"\n\
         SMTP_PORT=\"{}\"\n\
         EMAIL_FROM=\"{}\"\n\
         EMAIL_TO=\"{}\"\n\
         SMTP_AUTH=\"{}\"\n\
         SMTP_TLS=\"{}\"\n",
        config.email.smtp_host,
        config.email.smtp_port,
        config.email.from,
        config.email.to,
        auth,
        tls
    )
}

/// Generate a package-manager-specific ESP sync hook. Returns (path, content)
/// for pacman/apt/dnf, or None if hooks are disabled or type is None.
pub fn render_esp_hook(config: &Config) -> Option<(String, String)> {
    if !config.esp.hooks.enabled {
        return None;
    }

    let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);

    match config.esp.hooks.hook_type {
        HookType::Pacman => {
            let content = format!(
                "[Trigger]\n\
                 Type = Path\n\
                 Operation = Install\n\
                 Operation = Upgrade\n\
                 Target = usr/lib/modules/*/vmlinuz\n\
                 Target = boot/*\n\
                 \n\
                 [Action]\n\
                 Description = Syncing ESP mirrors after kernel update...\n\
                 When = PostTransaction\n\
                 Exec = {script_dir}/esp-sync.sh\n"
            );
            Some(("/etc/pacman.d/hooks/das-esp-sync.hook".to_string(), content))
        }
        HookType::Apt => {
            let content = format!("DPkg::Post-Invoke {{\"{script_dir}/esp-sync.sh\";}};\n");
            Some(("/etc/apt/apt.conf.d/99-das-esp-sync".to_string(), content))
        }
        HookType::Dnf => {
            let content = format!(
                "#!/usr/bin/env bash\n\
                 {GENERATED_HEADER}\
                 # DNF plugin hook — called after kernel/bootloader transactions\n\
                 {script_dir}/esp-sync.sh\n"
            );
            Some(("/etc/dnf/plugins/das-esp-sync".to_string(), content))
        }
        HookType::None => None,
    }
}

// ---------------------------------------------------------------------------
// GeneratedFiles — aggregates all rendered files
// ---------------------------------------------------------------------------

/// Collection of all generated files as (path, content) pairs.
pub struct GeneratedFiles {
    pub files: Vec<(String, String)>,
}

impl GeneratedFiles {
    /// Generate all operational files from a Config. Includes systemd units OR cron
    /// entries based on init system, plus btrbk.conf, backup-run.sh, email, and ESP hooks.
    pub fn generate(config: &Config) -> Self {
        let script_dir = format!("{}/lib/das-backup", config.general.install_prefix);
        let mut files = Vec::new();

        // btrbk.conf
        files.push((
            "/etc/das-backup/btrbk.conf".to_string(),
            render_btrbk_conf(config),
        ));

        // backup-run.sh wrapper (execs real script from scripts/ subdir)
        files.push((
            format!("{script_dir}/backup-run.sh"),
            render_backup_run(config),
        ));

        // Real production scripts (embedded in binary, config-driven via eval)
        let scripts_subdir = format!("{script_dir}/scripts");
        files.push((
            format!("{scripts_subdir}/backup-run.sh"),
            SCRIPT_BACKUP_RUN.to_string(),
        ));
        files.push((
            format!("{scripts_subdir}/backup-verify.sh"),
            SCRIPT_BACKUP_VERIFY.to_string(),
        ));
        files.push((
            format!("{scripts_subdir}/boot-archive-cleanup.sh"),
            SCRIPT_BOOT_ARCHIVE_CLEANUP.to_string(),
        ));

        // Scheduling: systemd OR cron
        match config.init.system {
            InitSystem::Systemd => {
                files.push((
                    "/etc/systemd/system/das-backup.service".to_string(),
                    render_systemd_service(config, false),
                ));
                files.push((
                    "/etc/systemd/system/das-backup.timer".to_string(),
                    render_systemd_timer(config, false),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-full.service".to_string(),
                    render_systemd_service(config, true),
                ));
                files.push((
                    "/etc/systemd/system/das-backup-full.timer".to_string(),
                    render_systemd_timer(config, true),
                ));
            }
            InitSystem::Sysvinit | InitSystem::Openrc => {
                files.push((
                    "/etc/cron.d/das-backup".to_string(),
                    render_cron_entry(config),
                ));
            }
        }

        // Email config
        if config.email.enabled {
            files.push((
                "/etc/das-backup/email.conf".to_string(),
                render_email_conf(config),
            ));
        }

        // ESP hook
        if let Some((path, content)) = render_esp_hook(config) {
            files.push((path, content));
        }

        Self { files }
    }

    /// Produce a newline-joined manifest of all generated file paths.
    pub fn manifest_content(&self) -> String {
        self.files
            .iter()
            .map(|(p, _)| p.as_str())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Parse a time string like "03:00" into (hour, minute).
fn parse_time(time_str: &str) -> (u32, u32) {
    let parts: Vec<&str> = time_str.split(':').collect();
    let hour = parts.first().and_then(|s| s.parse().ok()).unwrap_or(3);
    let min = parts.get(1).and_then(|s| s.parse().ok()).unwrap_or(0);
    (hour, min)
}

/// Parse a schedule string like "Sun 04:00" into (day_of_week, hour, minute).
/// Day of week: Sun=0, Mon=1, ..., Sat=6.
fn parse_schedule_with_day(schedule: &str) -> (u32, u32, u32) {
    let parts: Vec<&str> = schedule.split_whitespace().collect();
    if parts.len() == 2 {
        let dow = match parts[0].to_lowercase().as_str() {
            "sun" => 0,
            "mon" => 1,
            "tue" => 2,
            "wed" => 3,
            "thu" => 4,
            "fri" => 5,
            "sat" => 6,
            _ => 0,
        };
        let (hour, min) = parse_time(parts[1]);
        (dow, hour, min)
    } else {
        let (hour, min) = parse_time(parts[0]);
        (0, hour, min) // Default to Sunday
    }
}

// ---------------------------------------------------------------------------
// Tests (TDD — written first, implementation follows)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> Config {
        let mut config = Config::default();
        config.general.install_prefix = "/usr/local".to_string();
        config.sources.push(Source {
            label: "nvme-root".to_string(),
            volume: "/.btrfs-nvme".to_string(),
            subvolumes: vec!["@".to_string(), "@home".to_string()],
            device: "/dev/nvme0n1p2".to_string(),
            snapshot_dir: ".btrbk-snapshots".into(),
            target_subdirs: vec!["nvme".into()],
        });
        config.targets.push(Target {
            label: "primary-22tb".to_string(),
            serial: "ZXA0LMAE".to_string(),
            mount: "/mnt/backup-22tb".to_string(),
            role: TargetRole::Primary,
            retention: Retention {
                weekly: 4,
                monthly: 2,
                daily: 0,
                yearly: 0,
            },
            display_name: String::new(),
        });
        config
    }

    #[test]
    fn render_btrbk_conf_test() {
        let config = test_config();
        let result = render_btrbk_conf(&config);
        // Check volume, subvolume, target, retention, header
        assert!(result.contains("volume /.btrfs-nvme"), "missing volume");
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.trim().ends_with("@")),
            "missing subvolume @"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("subvolume") && l.contains("@home")),
            "missing subvolume @home"
        );
        assert!(
            result
                .lines()
                .any(|l| l.trim().starts_with("target") && l.contains("/mnt/backup-22tb")),
            "missing target /mnt/backup-22tb"
        );
        assert!(result.contains("4w 2m"), "missing retention 4w 2m");
        assert!(
            result.contains("# Generated by btrdasd setup"),
            "missing header"
        );
    }

    #[test]
    fn render_systemd_service_test() {
        let config = test_config();
        let result = render_systemd_service(&config, false);
        assert!(result.contains("ExecStart=/usr/local/lib/das-backup/backup-run.sh"));
        assert!(!result.contains("/hddRaid1/"));
        assert!(result.contains("# Generated by btrdasd setup"));
    }

    #[test]
    fn render_systemd_timer_test() {
        let config = test_config();
        let result = render_systemd_timer(&config, false);
        assert!(result.contains("OnCalendar=*-*-* 03:00:00"));
        assert!(result.contains("RandomizedDelaySec=1800"));
    }

    #[test]
    fn render_cron_entry_test() {
        let config = test_config();
        let result = render_cron_entry(&config);
        assert!(result.contains("0 3 * * *"));
        assert!(result.contains("/usr/local/lib/das-backup/backup-run.sh"));
    }

    #[test]
    fn render_backup_run_wrapper_test() {
        let config = test_config();
        let result = render_backup_run(&config);
        assert!(result.starts_with("#!/usr/bin/env zsh"));
        assert!(result.contains("exec"));
        assert!(result.contains("/usr/local/lib/das-backup/scripts/backup-run.sh"));
        assert!(result.contains("# Generated by btrdasd setup"));
    }

    #[test]
    fn generated_files_include_embedded_scripts() {
        let config = test_config();
        let generated = GeneratedFiles::generate(&config);
        let manifest = generated.manifest_content();
        assert!(
            manifest.contains("scripts/backup-run.sh"),
            "missing embedded backup-run.sh"
        );
        assert!(
            manifest.contains("scripts/backup-verify.sh"),
            "missing embedded backup-verify.sh"
        );
        assert!(
            manifest.contains("scripts/boot-archive-cleanup.sh"),
            "missing embedded boot-archive-cleanup.sh"
        );
    }

    #[test]
    fn generated_files_manifest() {
        let config = test_config();
        let generated = GeneratedFiles::generate(&config);
        let manifest = generated.manifest_content();
        assert!(manifest.contains("/etc/das-backup/btrbk.conf"));
        assert!(manifest.contains("backup-run.sh"));
        assert!(manifest.contains("das-backup.service"));
        assert!(manifest.contains("das-backup.timer"));
    }
}
