//! `btrdasd subvol` commands that change the config must leave `config.toml`
//! and `btrbk.conf` agreeing with each other. Before this, `subvol add` wrote
//! the config and nothing else, so the subvolume was "added" and still not
//! backed up until `setup --upgrade` was also run.

use std::path::Path;
use std::process::Command;

/// `second_source` adds a source `s2` on the same volume and snapshot
/// directory as `s`: the layout where two sources can resolve to the same
/// snapshot name, which is the only way a collision survives the per-source
/// name resolver.
fn write_config_with(dir: &Path, second_source: bool) -> std::path::PathBuf {
    let conf = dir.join("btrbk.conf");
    let s2 = if second_source {
        "[[source]]\nlabel = \"s2\"\nvolume = \"/vol\"\ndevice = \"UUID=abc\"\n[[source.subvolumes]]\nname = \"@other\"\n"
    } else {
        ""
    };
    let text = format!(
        r#"[general]
version = "0.7.22"
install_prefix = "/usr"
db_path = "{db}"
btrbk_conf = "{conf}"
[init]
system = "systemd"
[schedule]
incremental = "03:00"
full = "Sun 04:00"
randomized_delay_min = 30
[[source]]
label = "s"
volume = "/vol"
device = "UUID=abc"
[[source.subvolumes]]
name = "@"
{s2}[[target]]
label = "t"
serial = "X"
mount = "/mnt/t"
role = "primary"
[target.retention]
daily = 7
[email]
enabled = false
[gui]
enabled = false
"#,
        db = dir.join("index.db").display(),
        conf = conf.display(),
    );
    let path = dir.join("config.toml");
    std::fs::write(&path, text).unwrap();
    path
}

fn write_config(dir: &Path) -> std::path::PathBuf {
    write_config_with(dir, false)
}

fn btrdasd(args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_btrdasd"))
        .args(args)
        .output()
        .expect("spawn btrdasd")
}

#[test]
fn subvol_add_and_remove_regenerate_btrbk_conf() {
    let dir = tempfile::tempdir().unwrap();
    let config = write_config(dir.path());
    let config_s = config.to_str().unwrap();

    let out = btrdasd(&["subvol", "add", "s", "@home", "--config", config_s]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let conf = std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap();
    assert!(
        conf.contains("  subvolume             @home\n    snapshot_name       home\n"),
        "{conf}"
    );
    let saved = std::fs::read_to_string(&config).unwrap();
    assert!(saved.starts_with("# Generated by btrdasd setup"), "{saved}");

    let out = btrdasd(&["subvol", "remove", "s", "@home", "--config", config_s]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let conf = std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap();
    assert!(!conf.contains("@home"), "{conf}");
}

#[test]
fn subvol_set_manual_and_set_auto_keep_btrbk_conf_in_step() {
    let dir = tempfile::tempdir().unwrap();
    let config = write_config(dir.path());
    let config_s = config.to_str().unwrap();

    for action in ["set-manual", "set-auto"] {
        let out = btrdasd(&["subvol", action, "s", "@", "--config", config_s]);
        assert!(
            out.status.success(),
            "{action}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let conf = std::fs::read_to_string(dir.path().join("btrbk.conf"))
            .unwrap_or_else(|e| panic!("{action} left no btrbk.conf: {e}"));
        assert!(
            conf.contains("subvolume             @\n"),
            "{action}: {conf}"
        );
    }
}

#[test]
fn subvol_add_refuses_a_name_collision_and_changes_nothing() {
    let dir = tempfile::tempdir().unwrap();
    let config = write_config_with(dir.path(), true);
    let config_s = config.to_str().unwrap();
    assert!(
        btrdasd(&["subvol", "add", "s", "a/b", "--config", config_s])
            .status
            .success()
    );
    let before = std::fs::read_to_string(&config).unwrap();
    let conf_before = std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap();

    let out = btrdasd(&["subvol", "add", "s2", "a-b", "--config", config_s]);
    assert!(!out.status.success());
    assert!(String::from_utf8_lossy(&out.stderr).contains("snapshot name 'a-b'"));
    assert_eq!(std::fs::read_to_string(&config).unwrap(), before);
    assert_eq!(
        std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap(),
        conf_before
    );
}

#[test]
fn subvol_sync_exits_one_when_a_volume_cannot_be_read_and_two_without_a_config() {
    let dir = tempfile::tempdir().unwrap();
    let config = write_config(dir.path());
    // /vol is not a mountpoint on any test machine.
    let out = btrdasd(&["subvol", "sync", "--config", config.to_str().unwrap()]);
    assert_eq!(out.status.code(), Some(1));
    let text = String::from_utf8_lossy(&out.stdout);
    assert!(text.starts_with("SUBVOLUME SYNC\n"), "{text}");
    assert!(text.contains("VOLUMES NOT READ"), "{text}");
    // The library names the source and device before the reason.
    assert!(
        text.contains("/vol: source 's' names device 'UUID=abc': /vol is not mounted"),
        "{text}"
    );

    let out = btrdasd(&[
        "subvol",
        "sync",
        "--config",
        dir.path().join("none.toml").to_str().unwrap(),
    ]);
    assert_eq!(out.status.code(), Some(2));
}

#[test]
fn subvol_expire_prints_nothing_and_exits_zero_when_nothing_is_retired() {
    let dir = tempfile::tempdir().unwrap();
    let config = write_config(dir.path());
    let out = btrdasd(&[
        "subvol",
        "expire",
        "--config",
        config.to_str().unwrap(),
        "--db",
        dir.path().join("index.db").to_str().unwrap(),
    ]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(out.stdout.is_empty());
}

/// `subvol sync --dry-run --render-btrbk-conf` writes the btrbk.conf the real
/// run would leave into an existing file, and nothing else (bd
/// DAS-Backup-Manager-g17). `/vol` is not mounted here, so nothing is read,
/// the sync fails, and the real run would leave btrbk.conf as it is.
#[test]
fn sync_dry_run_renders_the_planned_btrbk_conf_into_an_existing_file() {
    let dir = tempfile::tempdir().unwrap();
    let config = write_config(dir.path());
    let config_s = config.to_str().unwrap();
    std::fs::write(dir.path().join("btrbk.conf"), "CURRENT\n").unwrap();
    let before = std::fs::read_to_string(&config).unwrap();
    let render = dir.path().join("planned.conf");
    std::fs::write(&render, "").unwrap();
    let render_s = render.to_str().unwrap();

    let out = btrdasd(&[
        "subvol",
        "sync",
        "--config",
        config_s,
        "--dry-run",
        "--render-btrbk-conf",
        render_s,
    ]);
    assert_eq!(out.status.code(), Some(1), "the volume was not read");
    assert_eq!(std::fs::read_to_string(&render).unwrap(), "CURRENT\n");
    assert_eq!(std::fs::read_to_string(&config).unwrap(), before);
    assert_eq!(
        std::fs::read_to_string(dir.path().join("btrbk.conf")).unwrap(),
        "CURRENT\n"
    );

    // Not without --dry-run: a real sync writes the real file.
    std::fs::write(&render, "").unwrap();
    let out = btrdasd(&[
        "subvol",
        "sync",
        "--config",
        config_s,
        "--render-btrbk-conf",
        render_s,
    ]);
    assert_eq!(out.status.code(), Some(2), "clap refuses the flag alone");
    assert_eq!(std::fs::read_to_string(&render).unwrap(), "");

    // Nothing readable would be left: no file to render, and the command fails.
    std::fs::remove_file(dir.path().join("btrbk.conf")).unwrap();
    let out = btrdasd(&[
        "subvol",
        "sync",
        "--config",
        config_s,
        "--dry-run",
        "--render-btrbk-conf",
        render_s,
    ]);
    assert_eq!(out.status.code(), Some(1));
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("no btrbk.conf to render"),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert_eq!(std::fs::read_to_string(&render).unwrap(), "");
}
